### ISSUE TITLE
install TKEStack failed

### ISSUE THREAD

**Issue by Noany** [tkestack/tke#106]
**What happened**:
1. install tke-installer by running tke-installer-x86_64-v1.0.1.run, it shows:
2020-01-13 03:08:12.073	INFO	Starting tke-installer at http://x.x.x.x:8080
[FAIL] Operation failed.
2. visit http://x.x.x.x:8080 to install TKEStack, but after clicking the installation button, we just get a blank page. It seems that something is wrong with /api/cluster request:
![image](https://user-images.githubusercontent.com/12050033/72231658-ac2c4c80-35f7-11ea-89df-0ad37f0b6427.png)

**What you expected to happen**:
successful installation or when the installation failed, I can get detail message about what happend. 

**How to reproduce it (as minimally and precisely as possible)**:
1. run tke-installer-x86_64-v1.0.1.run
2.visit http://x.x.x.x:8080 with the following configuration:
![image](https://user-images.githubusercontent.com/12050033/72231835-805d9680-35f8-11ea-8fb9-61afdd8aba98.png)
![image](https://user-images.githubusercontent.com/12050033/72231838-83f11d80-35f8-11ea-8a35-e8c42e120052.png)

**Anything else we need to know?**:
No

**Environment**:
- TKE version: 1.0.1
- Global or business cluster: global
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:
  Operating Systems: CentOS 7.5
  Memory: 251GB

**Comment by QianChenglong** [comment]
1. Check docker info `docker info`
2. Check docker log `docker log tke-installer`
3.Check tke-installer data `/opt/tke-installer/data/tke.{json,log}
