### ISSUE TITLE
没法添加节点

### ISSUE THREAD

**Issue by heyi-core** [tkestack/tke#1071]
**What happened**: 创建集群的时候没法添加节点, 报错信息:Machine.platform.tkestack.io "mc-6k7jgxft" is invalid: [spec: Invalid value: "": exec cmd "whoami" eror: dial tcp 192.168.1.132:22: i/o timeout, spec.user: Invalid value: "root": must be root or set sudo without password]

**What you expected to happen**: root账号密码都对, 本地能够登陆

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/16987074/106097949-25e79780-6173-11eb-9c74-2d559ae60ef4.png)

**Environment**:
- TKE version: 1.5
- Global or business cluster: 都有
- Kubernetes version (use `kubectl version`): 
- Install addons:
- Others:

**Comment by donald-sandoz** [comment]
我在tke1.7版本遇到同样的问题，有什么解决办法吗

**Comment by luckyboysmith** [comment]
> 我在tke1.7版本遇到同样的问题，有什么解决办法吗

你好，我也遇到了同样的问题，请问你那边解决了么，是怎么解决的呢
