### ISSUE TITLE
Extra Docker daemon argument conflicts with daemon.json

### ISSUE THREAD

**Issue by langyenan** [tkestack/tke#108]
**What happened**:
I added `insecure-registry=my-regsitry.com` as an extra docker daemon argument, `EnsureDocker` failed with following error:
```
Jan 14 14:58:12 VM_3_201_centos dockerd[18753]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: insecure-registries: (from flag: [my-regsitry.com], from file: [registry.tke.com default.registry.tke.com])
```

**What you expected to happen**:
my insecure registry should be merge into daemon.json

**Environment**:
- TKE version: v1.0.1

**Comment by QianChenglong** [comment]
Can be achieved by modifying the configuration template:
![image](https://user-images.githubusercontent.com/1881126/72401227-681b8200-3786-11ea-879d-bfc46a7d002d.png)
