### ISSUE TITLE
tke-install intall failed when disable monitoring

### ISSUE THREAD

**Issue by nashasha1** [tkestack/tke#109]
request has no response when disable monitoring.

![image](https://user-images.githubusercontent.com/9858380/72324576-3c48bf80-36e6-11ea-9b2f-7b82e2ca5b0c.png)

docker logs:

![image](https://user-images.githubusercontent.com/9858380/72324940-02c48400-36e7-11ea-969a-82ee36bf5479.png)

**Comment by QianChenglong** [comment]
thx, will be fixed
