### ISSUE TITLE
添加节点初始化失败

### ISSUE THREAD

**Issue by tgb7895** [tkestack/tke#1093]
添加节点初始化失败如何删除？？ 目前无法删除节点  一直显示初始化

**Comment by xiaosuiba** [comment]
try delete it with kubectl. 
`kubectl get machine`
`kubectl delete machine`

**Comment by slimhappy** [comment]
目前也遇到在添加节点环节卡住，节点一直处于初始化的状态。有找到方法解决吗?

**Comment by tgb7895** [comment]
> 目前也遇到在添加节点环节卡住，节点一直处于初始化的状态。有找到方法解决吗?

**Comment by tgb7895** [comment]
> 目前也遇到在添加先前的临时卡住，通常一直处于初始化的状态。有找到方法解决吗？

貌似多等一会自动消失
