### ISSUE TITLE
Only install nvidia-container-runtime on pGPU type node 

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#1127]
**What happened**:
vGPU node with nvidia-container-runtime does not work.

**What you expected to happen**:
Only install nvidia-container-runtime on pGPU type node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by Huimintai** [comment]
PR:https://github.com/tkestack/tke/pull/1586
