### ISSUE TITLE
kubeletExtraArgs 定义但是未使用

### ISSUE THREAD

**Issue by net-sniper** [tkestack/tke#1140]
**What happened**:

https://github.com/tkestack/tke/blob/master/pkg/platform/provider/baremetal/cluster/create.go#L797
```
	kubeletExtraArgs := p.getKubeletExtraArgs(c)
	if _, ok := kubeletExtraArgs["hostname-override"]; !ok {
		if !c.Spec.HostnameAsNodename {
			phase += fmt.Sprintf(" --node-name=%s", c.Spec.Machines[0].IP)
		}
	}
```
无效代码

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
I think this is not dead coed, pleas check https://github.com/tkestack/tke/pull/827

**Comment by net-sniper** [comment]
I misunderstood
