### ISSUE TITLE
tke-installer clean_old_data does not work as expected

### ISSUE THREAD

**Issue by MaDongdong99** [tkestack/tke#1158]
**What happened**:

正在运行的tke-installer会频繁刷新 data/tke.json,  按照安装脚本的清理顺序，在**删除tke.json**和**删除installer容器**之间，有可能再次被写入tke.json文件，达不到清理的目的

function clean_old_data() {
  echo "Step.4 clean old data [doing]"

  find $DATA_DIR/* |egrep -v "(custom_upgrade_resource)" | xargs rm -rf  >/dev/null 2>&1 || :
  docker rm -f tke-installer >/dev/null 2>&1 || :
  docker volume prune -f >/dev/null 2>&1 || :

  echo "Step.4 clean old data [ok]"
}

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
clean.sh have been updated,
please run `curl -s https://tke-release-1251707795.cos.ap-guangzhou.myqcloud.com/tools/clean.sh | sh` before reinstall tke-installer.

**Comment by leoryu** [comment]
Closed via https://github.com/tkestack/tke/blob/d66fb9a7b1e52d0895f21b05b342353044679944/build/docker/tools/tke-installer/install.sh#L132-L141
