### ISSUE TITLE
installer/platform-api panic when features/file not exists 

### ISSUE THREAD

**Issue by MaDongdong99** [tkestack/tke#1159]
**What happened**:

If setting tke.json with .cluster.features.files and file does not exist in installer or platform-api container,  it will panic when ValidateHooks. 

github.com/tkestack/tke/api/platform/validation/cluster.go:230  s, _ := os.Stat(f.Src)
github.com/tkestack/tke/api/platform/validation/cluster.go:231   if s.Mode().IsRegular() 
 
os.Stat will return nil when it not exists, and cause panic when s.Mode() called

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
clean.sh have been updated,
please run `curl -s https://tke-release-1251707795.cos.ap-guangzhou.myqcloud.com/tools/clean.sh | sh` before reinstall tke-installer.
