### ISSUE TITLE
tke-platform-api missing RBAC in v1.6.0

### ISSUE THREAD

**Issue by MaDongdong99** [tkestack/tke#1160]
**What happened**:

log of tke-platformapi

2021-03-30 07:54:34.804	ERROR	pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tke:default" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
2021-03-30 07:54:34.804	WARN	pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tke:default" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
2021-03-30 07:54:34.804	INFO	pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:tke:default" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope

-------
fixed when apply such ClusterRole and ClusterRoleBinding
---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        kubernetes.io/bootstrapping: rbac-defaults
      name: tke-default
    rules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        resources:
          - clusterrolebindings
          - clusterroles
        verbs: ["get", "update", "list", "watch"]
---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
      labels:
        kubernetes.io/bootstrapping: rbac-defaults
      name: tke-default
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: tke-default
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: tke

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by xiaosuiba** [comment]
I guess you're installing with '--no-ui'. I found the reason that they enabled webhook in v1.6.0, which will enable all `system:*` has full access to all resources in global cluster. I'm not sure is that an issue. Right now you should add an `authzWebhookAddr` in your config file to enable this. 
```yaml
"features": {
    "authzWebhookAddr": {
         "builtin": {}
   }
}
```

related issue: https://github.com/tkestack/tke/pull/1155

**Comment by MaDongdong99** [comment]
> I guess you're installing with '--no-ui'. I found the reason that they enabled webhook in v1.6.0, which will enable all `system:*` has full access to all resources in global cluster. I'm not sure is that an issue. Right now you should add an `authzWebhookAddr` in your config file to enable this.
> 
> ```yaml
> "features": {
>     "authzWebhookAddr": {
>          "builtin": {}
>    }
> }
> ```
> 
> related issue: #1155

Yes, this works. But I don't get the point:  is this Enable or Disable webhook ?  If I set features.authzWebhookAddr.builtin: {} or not , the tke-auth-api has the same configuration of  "spec":{"user":"system:*",...}

**Comment by xiaosuiba** [comment]
> > I guess you're installing with '--no-ui'. I found the reason that they enabled webhook in v1.6.0, which will enable all `system:*` has full access to all resources in global cluster. I'm not sure is that an issue. Right now you should add an `authzWebhookAddr` in your config file to enable this.
> > ```yaml
> > "features": {
> >     "authzWebhookAddr": {
> >          "builtin": {}
> >    }
> > }
> > ```
> > 
> > 
> > related issue: #1155
> 
> Yes, this works. But I don't get the point: is this Enable or Disable webhook ? If I set features.authzWebhookAddr.builtin: {} or not , the tke-auth-api has the same configuration of "spec":{"user":"system:*",...}

tke-auth-api enabled ABAC, and the default abac rules like
`{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"system:*","namespace":"*", "resource":"*","apiGroup":"*", "group": "*", "nonResourcePath":"*"}}`

**Comment by MaDongdong99** [comment]
> > > I guess you're installing with '--no-ui'. I found the reason that they enabled webhook in v1.6.0, which will enable all `system:*` has full access to all resources in global cluster. I'm not sure is that an issue. Right now you should add an `authzWebhookAddr` in your config file to enable this.
> > > ```yaml
> > > "features": {
> > >     "authzWebhookAddr": {
> > >          "builtin": {}
> > >    }
> > > }
> > > ```
> > > 
> > > 
> > > related issue: #1155
> > 
> > 
> > Yes, this works. But I don't get the point: is this Enable or Disable webhook ? If I set features.authzWebhookAddr.builtin: {} or not , the tke-auth-api has the same configuration of "spec":{"user":"system:*",...}
> 
> This will enable webhook in apiserver, which will send subjectreview to tke-auth-api. tke-auth-api enabled ABAC, and the default abac rules like
> `{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"system:*","namespace":"*", "resource":"*","apiGroup":"*", "group": "*", "nonResourcePath":"*"}}` which would grant permission for any serviceaccount to access to any resource in the cluster.

Ok, I will follow this change
