### ISSUE TITLE
Hope to get kubeconfig when executing post-cluster-ready hook

### ISSUE THREAD

**Issue by davidwtf** [tkestack/tke#120]
**What would you like to be added**:

We hope to get kubeconfig when executing `post-cluster-ready` hook.

**Why is this needed**:

Because we need using kubectl to do extra jobs in `post-cluster-ready` script.

We suggest moving `writeKubeconfig` handler ahead of `postClusterReadyHook`.

**Comment by QianChenglong** [comment]
Reasonable suggestion, support for next version.
