### ISSUE TITLE
请问如何重启TKE控制台

### ISSUE THREAD

**Issue by fano36** [tkestack/tke#1204]
**What would you like to be added**:
在官方安装文档中没有找到关于重启控制台的说明
**Why is this needed**:
重启服务器的docker之后，控制台无法访问

**Comment by xiaosuiba** [comment]
maybe you could put more informations here.
`kubectl -n tke get pod` 
and logs of gateway pod.

**Comment by fano36** [comment]
> 也许您可以在此处放置更多信息。
> `kubectl -n tke get pod`
> 和网关pod的日志。

If my server goes down, do I need to start all tkepods?
