### ISSUE TITLE
webtty access pod not work when api upgrade to 1.19

### ISSUE THREAD

**Issue by leoryu** [tkestack/tke#1209]
**What happened**:

![image](https://user-images.githubusercontent.com/34183243/115364519-0bfba500-a1f6-11eb-9e33-db53ca02f902.png)

remote access doesn't work when api is upgraded to 1.19.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by huxiaoliang** [comment]
@leoryu  please find out the root cause and fix
