### ISSUE TITLE
TKE接入LDAP遇到问题

### ISSUE THREAD

**Issue by luckyboysmith** [tkestack/tke#1215]
**What happened**:
情况描述：
在tke安装过程中，认证方式选择 TKE提供
在tke安装后，希望接入LDAP，参考官方文档进行接入，文档链接 https://tkestack.github.io/docs/faq/permission/ldap-oidc.html
在tke1.3和tke1.4均做了测试，
接入过程中遇到问题，具体操作流程如下：
1.kubectl get cm -n tke tke-auth-api -o yaml并增加配置
增加后的结果如下图所示
![image](https://user-images.githubusercontent.com/23690787/115530882-c22ebf80-a2c6-11eb-8a2c-272b0d3c60ed.png)

2.准备ldap配置文件
此处不展示ldap配置文件了

3.调用api
我用的postman来调用，结果如下图所示
![image](https://user-images.githubusercontent.com/23690787/115531197-1639a400-a2c7-11eb-9872-31d287e5c6f0.png)

如上图所示，返回结果为 the server does not allow this method on the requested resource
在tke1.3和tke1.4上做了尝试，结果相同

**What you expected to happen**:
希望能将tke接入LDAP
**How to reproduce it (as minimally and precisely as possible)**:
只要按照当前官方文档中的操作，应该就可以得到与我一致的结果
**Anything else we need to know?**:
我在TKEStack Group群中有咨询过如何接入LDAP，如果有问题未描述清楚 或者 没表述明白的地方，可以联系我

**Environment**:
- TKE version:1.3 和 1.4
- Global or business cluster: b
- Kubernetes version (use `kubectl version`):v1.18.3
- Install addons:
- Others:

**Comment by xiaosuiba** [comment]
you should put the name of identityprovider in request body, not in path. 
`POST` `https://{your-host}/apis/auth.tkestack.io/v1/identityproviders`
Only `PUT` method could be used with name in path.
