### ISSUE TITLE
希望 platform-api 提供 proxy 能力能够支持 networking.k8s.io v1beta1 Ingresses 的 status 和 events 子资源

### ISSUE THREAD

**Issue by defydahui** [tkestack/tke#1256]
**What would you like to be added**:
希望 platform-api 向业务集群 proxy 资源请求时，对于 Ingresses 资源，能够像 extensions v1beta1 一样，支持 ingress/status 和 ingress/events.
参考 https://github.com/defydahui/tke master 分支的如下提交：
fix: networking v1beta1 do NOT support status and event
0da0d41a26bbfc62021b38621d6c9d39d265f9fa
**Why is this needed**:
我们在使用 TKEStack 管理业务集群，并且由 paltform-api 往 业务集群转发 资源请求。
在业务的 Ingresses 由 apigroup extention v1beta1 升级到 networking.k8s.io v1beta1 之后，我们发现原来支持的 ingress/status 和 ingress/events 无法正常工作。

**Comment by huxiaoliang** [comment]
fixed :https://github.com/tkestack/tke/pull/1257
