### ISSUE TITLE
put external ip and to api server certSANs 

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1307]

**Comment by huxiaoliang** [comment]
workaround is : https://github.com/kubernetes/kubeadm/issues/1447#issuecomment-490494999

**Comment by huxiaoliang** [comment]
@TomatoAres， please take a look this.

**Comment by TomatoAres** [comment]
We need to know VM's external IP, but tke can not get this IP.

Some public cloud scenarios are   not appropriate，such as:

1.  VM without external IP
2.  VM with a elastic external IP

**Comment by TomatoAres** [comment]
Close this issue.@huxiaoliang

**Comment by huxiaoliang** [comment]
just handle the global cluster console external ip and domain is ok for me

**Comment by TomatoAres** [comment]
I got it
