### ISSUE TITLE
tkestack pod state in `NodeAffinity` after reboot host 

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1330]
In all-in-one deploy mode, after reboot host,  many of pods in `tke` ns state in `NodeAffinity` , run below command to workaround 

```
 get pod -A | grep NodeAffinity | awk '{print $2}' |xargs kubectl delete pod -n tke
```

**Comment by leoryu** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/92067
https://github.com/kubernetes/kubernetes/pull/94087
