### ISSUE TITLE
status code 404 and 502 in tke-1.1.0

### ISSUE THREAD

**Issue by jianzzz** [tkestack/tke#134]
**What happened**:
- status Code: 404 Not Found
 request http://console.tke.com/apis/apps/v1beta2/namespaces/default/deployments

- Status Code: 502 Bad Gateway
request http://console.tke.com/apis/auth.tkestack.io/v1/apikeys

**What you expected to happen**:
Status Code: 200

**How to reproduce it (as minimally and precisely as possible)**:
use tke-installer-x86_64-v1.1.0.run to install, and visit the console

**Environment**:
- TKE version: 1.1.0
- Global or business cluster: 1.16.6

**Comment by QianChenglong** [comment]
One issue for one problem, please.
