### ISSUE TITLE
Unable to completely delete machine when delete cluster

### ISSUE THREAD

**Issue by pavlelee** [tkestack/tke#1351]
**What happened**:
When i delete cluster cr, tkestack sync delete machine, but the finalize immediately emptied. make machine delete k8s node error by cluster cr. 

https://github.com/tkestack/tke/blob/c13ac23ddf2684c5f0e0c72086f5141cfc0c8586/pkg/platform/controller/cluster/deletion/cluster_deleter.go#L123

https://github.com/tkestack/tke/blob/c13ac23ddf2684c5f0e0c72086f5141cfc0c8586/pkg/platform/controller/cluster/deletion/cluster_deleter.go#L255

https://github.com/tkestack/tke/blob/5dcd1c2a662bf625e3b5b9b035e0e4c822d94b26/pkg/platform/controller/machine/deletion/machine_deleter.go#L294

![image](https://user-images.githubusercontent.com/5382358/121161227-5ce75b80-c87f-11eb-9f6b-cd1e636dde8d.png)
![image](https://user-images.githubusercontent.com/5382358/121161356-7dafb100-c87f-11eb-8daa-81d51dc22852.png)
![image](https://user-images.githubusercontent.com/5382358/121161705-d8490d00-c87f-11eb-907c-7b12941fb442.png)

**What you expected to happen**:
delete ok

**How to reproduce it (as minimally and precisely as possible)**:
delete cluster maybe reproduce it

**Anything else we need to know?**:

**Environment**:
- TKE version: 
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by pavlelee** [comment]
Design:
1、remove deleteMachine from cluster deletion
2、add machine ownerReference && ownerReference.blockOwnerDeletion=true 
3、normal delete cluster，k8s gc will auto delete machine. if machine deleting, cluster keep terminating.

@huxiaoliang

**Comment by huxiaoliang** [comment]
@pavlelee  I am ok on you design

**Comment by huxiaoliang** [comment]
@TomatoAres， please take a look this.

**Comment by pavlelee** [comment]
https://github.com/tkestack/tke/pull/1378

@TomatoAres I found new problem: call sdk delete cluster without deleteOptions.propagationPolicy, clustercredentials/machines have not garbage collection. but @huxiaoliang confirm that tkestack work good without options, I test not work, you should confirm this.

**Comment by huxiaoliang** [comment]
@TomatoAres  please update the latest status to this issue

**Comment by huxiaoliang** [comment]
@TomatoAres  please append the root case for his issue

**Comment by TomatoAres** [comment]
> @TomatoAres please append the root case for this issue

TKE machine controller doesn't watch delete machine operator. 

Machine controller use kubernetes add terminating status to  machine and this will trigger update operator.

Then machine controller to deal with this update callback, and the callback is  linked to `machine.status.phase`.

So we need to check the `machine.status.phase` `Not Terminating->Terminating`, to execute a delete machine callback function.

**Comment by huxiaoliang** [comment]
@TomatoAres  above analysis make sense, but still don't don't know why `delete cluster xxx` doesn't work but `delete machine xxx` works well, please correct me, thanks.

**Comment by TomatoAres** [comment]
> @TomatoAres above analysis make sense, but still don't don't know why `delete cluster xxx` doesn't work but `delete machine xxx` works well, please correct me, thanks.

Root cause is deleting cluster make cluster terminating.

Delete machine callback has `deleteNode` function, but some [cluster terminating will block node delete](https://github.com/tkestack/tke/blob/cb69ab790542d5b7a75023e6302e11679945ca5c/pkg/platform/controller/machine/deletion/machine_deleter.go#L298).  

Sometimes  [time check](https://github.com/tkestack/tke/blob/cb69ab790542d5b7a75023e6302e11679945ca5c/pkg/platform/controller/machine/machine_controller.go#L132) will forbid events enqueue.
