### ISSUE TITLE
tke的prometheus如何增加web ui页面访问

### ISSUE THREAD

**Issue by luckyboysmith** [tkestack/tke#1352]
**What happened**:
在tke的使用过程中，准备  增加一些自定义监控指标，
在增加自定义监控指标过程中，撰写的PromQL难以校验是否正确，目前是通过 修改tke-platform-controller、tke-monitor-controller后 make image，进而 更新tke平台上的tke-platform-controller、tke-monitor-controller镜像版本来进行校验
希望能通过web-ui方式访问prometheus-k8s，方便进行PromQL正确性的验证，但是
尝试以web ui方式访问prometheus-k8s pod，但是无法访问

因为个人也是边摸索边写，习惯边校验边做，在网上看的博客 prometheus的9090端口是有一个简单的web-ui界面的，但是尝试访问tke安装的Prometheus的web-ui界面无法访问，做了一些尝试 也没解决，希望得到帮助
![image](https://user-images.githubusercontent.com/23690787/121186623-e146d800-c899-11eb-8048-4e2fb9907fb8.png)

**What you expected to happen**:

希望能以web-ui方式访问prometheus 
或者 是否存在简单易行的 校验新增的自定义监控指标PromeQL的方法？

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.3
- Global or business cluster: bussiness
- Kubernetes version (use `kubectl version`): 1.8
- Install addons: Prometheus
- Others:

**Comment by xiaosuiba** [comment]
You can use NodePort type for `prometheus` service in `kube-system`:
1. ` kubectl patch svc prometheus -n kube-system --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'`
2. `kubectl get svc -n kube-system prometheus`
```
NAME         TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
prometheus   NodePort   192.168.255.94   <none>        9090:31197/TCP   20h
```
here `31197` is your nodeport.
3. visit prometheus via {hostIP}:{NodePort}

For a quickhand to update the scrape config of prometheus, you can update `prometheus-k8s-additional-scrape-config` secret in `kube-system` without rebuilding tke-monitor.

**Comment by luckyboysmith** [comment]
> You can use NodePort type for `prometheus` service in `kube-system`:
> 
> 1. ` kubectl patch svc prometheus -n kube-system --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'`
> 2. `kubectl get svc -n kube-system prometheus`
> 
> ```
> NAME         TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
> prometheus   NodePort   192.168.255.94   <none>        9090:31197/TCP   20h
> ```
> 
> here `31197` is your nodeport.
> 3. visit prometheus via {hostIP}:{NodePort}
> 
> For a quickhand to update the scrape config of prometheus, you can update `prometheus-k8s-additional-scrape-config` secret in `kube-system` without rebuilding tke-monitor.

thanks!
