### ISSUE TITLE
cluster controller log dump get client set error aways

### ISSUE THREAD

**Issue by pavlelee** [tkestack/tke#1366]
**What happened**:
cluster controller log dump get client set error aways
![image](https://user-images.githubusercontent.com/5382358/121987710-9b26d280-cdcb-11eb-88d5-1864226c2359.png)

**What you expected to happen**:
not dump this error

**How to reproduce it (as minimally and precisely as possible)**:
cat /log/path.log |grep 'can't find valid address'

**Anything else we need to know?**:

**Environment**:
- TKE version: master
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by pavlelee** [comment]
https://github.com/tkestack/tke/blob/f0333962e52025c42e1ef7b445bace948d50189a/pkg/platform/controller/cluster/cluster_controller.go#L257

this code trigger the problem

**Comment by TomatoAres** [comment]
Maybe your cluster has some wrong status, can you execute this command: 

 `kubectl get clusters cls-4blvkc7 -o jsonpath={.status.addresses} | jq`

then comment the command result here

**Comment by pavlelee** [comment]
in tkestack, error is 'sync ClusterMachine node label error' @TomatoAres
