### ISSUE TITLE
tkestack upgrade case verify

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1379]
- please verify tkestack upgrade case  by CLI  `--upgrade` and append the result

1. tkestack 1.5 ->  tkestack 1.6 
2. tkestack 1.6 ->  tkestack 1.7

- 2  reference,  please update below doc if any
 1. https://github.com/tkestack/tke/blob/master/docs/design-proposals/cluster-upgrade.md

**Comment by hustclf** [comment]
I would like take this issue.

**Comment by leoryu** [comment]
has been verified.
