### ISSUE TITLE
根据API使用指引调用TKE API失败

### ISSUE THREAD

**Issue by luckyboysmith** [tkestack/tke#1400]
**What happened**:
你好，
当我根据API使用指引 https://tkestack.github.io/docs/develop/api.html
调用TKE API失败，
目前 通过postman可以请求k8s的api，截图如下：
![image](https://user-images.githubusercontent.com/23690787/124432320-144e8f80-dda4-11eb-8d9a-194e00391c07.png)
当我根据API使用指引，请求TKE自定义的api时候，返回结果与预期不符
![image](https://user-images.githubusercontent.com/23690787/124432484-43650100-dda4-11eb-81f6-933c4b20b42f.png)

尝试访问其他API，
参照/api/openapi/zz_generated.openapi.go 中GetOpenAPIDefinitions方法
请求诸如 k8s.io/api/apps/v1.Deployment、k8s.io/api/apps/v1.ReplicaSet、tkestack.io/tke/api/logagent/v1.LogAgentList
返回结果如下图所示
![image](https://user-images.githubusercontent.com/23690787/124432766-8d4de700-dda4-11eb-8378-41c5537bb058.png)

目前 束手无策，希望得到帮助，谢谢

**What you expected to happen**:
正常调用tke platform api并返回正确结果
**How to reproduce it (as minimally and precisely as possible)**:

通过postman 请求 https://ip:port/platform/apis/platform.tkestack.io/v1/clusters

**Anything else we need to know?**:
目前 请求k8s的api是正常的，如第一张图所示，请求 /api/v1/nodes是可以正常返回的，但是请求TKE自定义的api返回信息与预期不符，是哪个地方操作的不对么
此外，TKE自定义的api 请求路径是在/api/openapi/zz_generated.openapi.go 中GetOpenAPIDefinitions方法，我应该是可以通过postman请求的，对么？
希望得到指点，感谢
**Environment**:
- TKE version:1.3
- Global or business cluster:global
- Kubernetes version (use `kubectl version`):1.8
- Install addons:
- Others:

**Comment by xiaosuiba** [comment]
The api invoking method in document is broken. Try invoke tke api as the frontend js do:
1. Retrieve cookie with username and password:
```bash
curl --location --request POST 'http://{GATEWAY_IP}/apis/gateway.tkestack.io/v1/tokens' \
--header 'Content-Type: application/json' \
--form 'username={YOUR_USERNAME}' \
--form 'password={YOUR_PASSWORD}'
```
2. Call tke api with cookie setted:
```bash
curl --location --request GET 'http://{GATEWAY_IP}/apis/platform.tkestack.io/v1/clusters' \
--header 'Cookie: tke=YOUR_COOKIED_RETRIEVED'
```
You could request other resources as above.

**Comment by luckyboysmith** [comment]
> The api invoking method in document is broken. Try invoke tke api as the frontend js do:
> 
> 1. Retrieve cookie with username and password:
> 
> ```shell
> curl --location --request POST 'http://{GATEWAY_IP}/apis/gateway.tkestack.io/v1/tokens' \
> --header 'Content-Type: application/json' \
> --form 'username={YOUR_USERNAME}' \
> --form 'password={YOUR_PASSWORD}'
> ```
> 
> 1. Call tke api with cookie setted:
> 
> ```shell
> curl --location --request GET 'http://{GATEWAY_IP}/apis/platform.tkestack.io/v1/clusters' \
> --header 'Cookie: tke=YOUR_COOKIED_RETRIEVED'
> ```
> 
> You could request other resources as above.

感谢指点
