### ISSUE TITLE
move manifests to provider-res

### ISSUE THREAD

**Issue by leoryu** [tkestack/tke#1409]
<img width="382" alt="企业微信截图_fad90ac7-4640-4826-9f42-58427037a9aa" src="https://user-images.githubusercontent.com/34183243/125016416-eae37b80-e0a3-11eb-88a1-cf51cda728a6.png">

**Comment by Huimintai** [comment]
Already removed gpu-manager manifests to provider-res image:
```
# docker run -it --rm --entrypoint=sh docker.io/tkestack/provider-res:v1.21.4-1
/data #
/data # ls res/
cilium/       containerd/   gpu-manager/  linux-amd64/  linux-arm64/
```
