### ISSUE TITLE
upgrade cisoperator to v1.2.0

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1411]
docker hub: https://hub.docker.com/r/tkestack/csi-provisioner/tags?page=1&ordering=last_updated
but codes: https://github.com/tkestack/tke/blob/master/pkg/platform/provider/baremetal/phases/csioperator/images/images.go#L51

take below pr as example: https://github.com/tkestack/tke/pull/1129

**Comment by TomatoAres** [comment]
Now csi-operator version is [v1.2.0](https://github.com/tkestack/tke/blob/38a3797ddc4034b643455a3e20c233b526308ad9/pkg/platform/provider/baremetal/phases/csioperator/images/images.go#L51)

So it is not a bug,please close this issue @huxiaoliang .
