### ISSUE TITLE
TKE extension plugin description rendor failed.

### ISSUE THREAD

**Issue by TomatoAres** [tkestack/tke#1416]
**What happened**:

When I add a addon in TKEStack, some addon has no description, such as `IPAM`

![addon-description](https://user-images.githubusercontent.com/34213033/125883775-e6fda7f6-d463-411d-b559-4f6fe20b4209.png)

In this code repo, I find the description is exist：<https://github.com/tkestack/tke/tree/master/hack/addon/readme>

Maybe the reason is render exception.

**What you expected to happen**:

Render description successfully:

![success](https://user-images.githubusercontent.com/34213033/125884044-0baf45a2-c131-41e3-abfc-d50d5bc8791c.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by huxiaoliang** [comment]
@TomatoAres what is the status for this issue? if the ci faild, please ask related guys to fix  or re-trigger rather than leave it here for ever.
