### ISSUE TITLE
console.tke.com:8080/platform 无法使用

### ISSUE THREAD

**Issue by svlys** [tkestack/tke#1423]
如何使用console.tke.com:8080/platform 接口进行API访问，主节点端口8080没有启动。
以下指引，不是很清晰
TKEStack上各种资源的接口均以 Kubernetes 原生 API 的形式提供，所有接口使用统一的前缀: http://console.tke.com:8080/platform，请求中需要将上一步申请的访问凭证以"Authorization: Bearer ${访问凭证}"的形式放入 header。

**Comment by leoryu** [comment]
create an access token and set it to  /etc/kubernetes/tke-token

curl -sk -H "Authorization: Bearer $(cat  /etc/kubernetes/tke-token)" -H "Content-Type:application/json"  -H "X-TKE-ClusterName:global" https://127.0.0.1:6443/apis/platform.tkestack.io/v1/clusteraddontypes | jq -r .items[].metadata.name

**Comment by svlys** [comment]
目前问题已解决，8080端口默认没有开
通过kubectl proxy --port=8080 代理可用
使用https://jimmysong.io/kubernetes-handbook/guide/auth-with-kubeconfig-or-token.html配置token

**Comment by htlabc** [comment]
没有/platform这个地址的处理，k8s的api也没找到 你是怎么访问 http://ip:8080/platform这个地址
