### ISSUE TITLE
请问tke 里面的 超售比 怎么度量

### ISSUE THREAD

**Issue by chenmins** [tkestack/tke#1468]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/2321767/128822066-0051fa8e-32ee-4113-a4e1-5b875ee9e552.png)

**Why is this needed**:
求解释说明，谢谢

**Comment by xiaosuiba** [comment]
It's a pure frontend trick, the code is here in: 
https://github.com/tkestack/tke/blob/master/web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx#L997
```golang
      if (oversoldRatio.cpu) {
        cpuRequest = (+cpuLimit * 1.0) / +oversoldRatio.cpu + '';
      }
      if (oversoldRatio.memory) {
        memRequest = (+memLimit * 1.0) / +oversoldRatio.memory + '';
      }
```
which simply means:
* If you set oversoldRatio, your `cpuRequest` and `memRequest` will be scaled to `limitValue/oversoldRatio`.
