### ISSUE TITLE
add counter for retry test case

### ISSUE THREAD

**Issue by leoryu** [tkestack/tke#1489]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by TomatoAres** [comment]
I added a counter where it often goes wrong in #1491.

Maybe this issue could be closed @leoryu
