### ISSUE TITLE
当 spec.features.containerRuntime 不存在时无法确定容器运行时到底是什么

### ISSUE THREAD

**Issue by jo-hnny** [tkestack/tke#1550]
**What happened**:
当 spec.features.containerRuntime 不存在时，新版本的集群运行时为containerd，老版本为docker，不统一

**What you expected to happen**:
最好是所有集群都含有spec.features.containerRuntime 字段，以确保集群运行时组件是显示确定的

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by Huimintai** [comment]
PR to fix this issue here: https://github.com/tkestack/tke/pull/1553
