### ISSUE TITLE
revision history tab of cronjob is loading all the time

### ISSUE THREAD

**Issue by JiaYongfei** [tkestack/tke#1574]
**What happened**:
Revision history tab of cronjob is loading all the time. Click retry link after it failed, but no request was sent out.
![wecom-temp-da7e0121047d6fa2c6fc243453b302a9](https://user-images.githubusercontent.com/10513152/133411996-bfe2c601-cda8-4db4-8a0a-bb3adcc7d62a.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- TKE version: 1.21
- Global or business cluster: business

**Comment by leoryu** [comment]
cronjob doesn't have Revision history, this tab should be hiden.

Manage the rollout of a resource.
  
 Valid resource types include:

  *  deployments
  *  daemonsets
  *  statefulsets
