### ISSUE TITLE
tke新加节点报错

### ISSUE THREAD

**Issue by luckyboysmith** [tkestack/tke#1625]
**What happened**:
tke1.7 新建集群时报错，提示
![image](https://user-images.githubusercontent.com/23690787/136954728-cd25baf1-de9b-40dd-87e7-1ae88b31147a.png)

Cluster.platform.tkestack.io "cls-lq2kcs4g" is invalid: [spec.machines[0]: Invalid value: "": exec cmd "whoami" eror: dial tcp XXXXXXX:22: i/o timeout, spec.machines[0].user: Invalid value: "root": must be root or set sudo without password]

在其他环境安装过tke1.7，当时没这个问题的，这次在内网安装测试环境，遇到了这个问题，账号和密码都是对的

**What you expected to happen**:能够成功新加节点

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
这个节点上，我之前安装过tke1.3，是没问题的，由于生产环境已经是tke1.7，就想着把测试环境也升级到1.7，结果升级报错

**Environment**:
- TKE version:1.7
- Global or business cluster:global
- Kubernetes version (use `kubectl version`):1.19.7
- Install addons:
- Others:

**Comment by leoryu** [comment]
please check in your tke-platform-controller pod cloud ssh in your target node. Log shows that accessing your node port 22  in pod timeout.
