### ISSUE TITLE
安装installer节点报错

### ISSUE THREAD

**Issue by qq383199165** [tkestack/tke#1671]
**What happened**:

Step.1 preflight
root: yes
check docker status
available disk space(/opt):  60 GiB
available disk space(/var/lib):  60 GiB
Step.2 check containerd status
Step.3 load tke-installer image [in process]
unpacking docker.io/tkestack/tke-installer-arm64:v1.8.0 (sha256:a57d12e49c9f3acd5a495f867a8dfa60e20c38af45abd7e2eceb4934c90a9e11)...done
unpacking overlayfs@sha256:a57d12e49c9f3acd5a495f867a8dfa60e20c38af45abd7e2eceb4934c90a9e11 (sha256:a57d12e49c9f3acd5a495f867a8dfa60e20c38af45abd7e2eceb4934c90a9e11)...done
unpacking docker.io/tkestack/registry-arm64:2.7.1 (sha256:55fd6043fdc85039cadaae3b14dd3925adad27252b6f11c72d2ae88235e17198)...done
unpacking overlayfs@sha256:55fd6043fdc85039cadaae3b14dd3925adad27252b6f11c72d2ae88235e17198 (sha256:55fd6043fdc85039cadaae3b14dd3925adad27252b6f11c72d2ae88235e17198)...done
Step.3 load tke-installer image [done]
Step.4 clean old data [in process]
Step.4 clean old data [done]
Step.5 start tke-installer [in process]
FATA[0002] OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/default/6d1ce533149e35f1c8198b2b87735722f72ecd58142aaadea731199ee91fcd8a/log.json: no such file or directory): fork/exec /usr/local/sbin/runc: exec format error: unknown
[FAIL] Operation failed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.8.0
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
Is runc on your node?

**Comment by qq383199165** [comment]
> Is runc on your node?

root@nvidia:/usr/local/sbin# which runc
/usr/local/sbin/runc

yes, it's on my node. But It doesn't seem to be working. When i 
docker run hello-world
It also reports the same error:
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/b983a094c7efe286ac4dcc66400625f5e8ad733844b003c4166a61cfcfab27c2/log.json: no such file or directory): fork/exec /usr/local/sbin/runc: exec format error: unknown.
ERRO[0000] error waiting for container: context canceled

I'm a green hand and I don't know why. Thank you for your reply.

**Comment by qq383199165** [comment]
The problem was solved after I reinstalled the runC
