### ISSUE TITLE
miss cluster status version, etc from cluster list by kubectl

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#1688]
<img width="326" alt="cluster_list" src="https://user-images.githubusercontent.com/3296885/144191748-5e0d6aab-df68-4bc8-97f1-3f67ac2bbb83.png">

**Comment by pavlelee** [comment]
see 
https://github.com/tkestack/tke/blob/bc9ff67c5e8c81883036eb1d3dccc3b8cbbd8b4b/pkg/platform/registry/cluster/storage/storage.go#L77

https://github.com/tkestack/tke/blob/36a5b87f7fec5f79616b7a1182744b70335304a7/pkg/platform/registry/cluster/storage/table.go#L32
