### ISSUE TITLE
controller 写法问题 

### ISSUE THREAD

**Issue by cuisongliu** [tkestack/tke#1693]
https://github.com/tkestack/tke/blob/784381b58c05a22d0a2f2a6bdd6d7af15d9fe56a/pkg/platform/controller/cluster/cluster_controller.go#L295

问一下，这块这么写的用意是什么？按照声明式api不是直接update or create 就可以么，是有特别的用意么？

**Comment by leoryu** [comment]
这块作用应该和你说的update or create一样，收敛到一个地方根据资源对象状态选择走update/create/delete

**Comment by cuisongliu** [comment]
我感觉不是根据deletetime 做删除，然后剩下的都是在更新资源么，出于什么目的根据status的数据判断update/create/delete？我的理解status是存只读数据的啊

**Comment by leoryu** [comment]
这里的delete不是删除api resource，而是执行我们自己的delete逻辑，用户将资源状态改为ClusterTerminating后，controler先改成这个状态后执行delete逻辑，如删除一些依赖资源等等，create，update类似

**Comment by cuisongliu** [comment]
> 这里的delete不是删除api resource，而是执行我们自己的delete逻辑，用户将资源状态改为ClusterTerminating后，controler发现这个状态后执行delete逻辑，如删除一些依赖资源等等，create，update类似

我是不太明白为啥要通过资源状态判断？有什么特殊考虑么，而不是通过api 本身去判断的？

**Comment by leoryu** [comment]
这里是controller的逻辑，api本身判断完能做什么？api只是改etcd里的内容，除此以外什么也干不了，删除node上的网卡，或是目标集群上的一些资源，这些api能去干吗？如果你有什么好的意见可以提交你的code来review下

**Comment by cuisongliu** [comment]
https://github.com/kubesphere/kubesphere/blob/6ed02d3059a7dd22a7c8e6d4f75e2363780a7b22/pkg/controller/cluster/cluster_controller.go#L432

我之前写controller都是大概这样的逻辑，所以不大理解，我的感觉status是存数据的，而并不是通过status来控制增删改查。所以不大理解这样做的初衷，是不是咱这快逻辑有什么特殊考虑。

通过deletetime来控制是否删除，剩下的都是update操作，不一定是只当做CRD的操作，也可以操作其他资源什么的，只是判断的标准是当前CRD的meta的数据而已。你之前说“用户将资源状态改为ClusterTerminating后” 为什么不是用户执行“kubectl delete cluster xxxx”这样来控制的？

**Comment by leoryu** [comment]
> https://github.com/kubesphere/kubesphere/blob/6ed02d3059a7dd22a7c8e6d4f75e2363780a7b22/pkg/controller/cluster/cluster_controller.go#L432
> 
> 我之前写controller都是大概这样的逻辑，所以不大理解，我的感觉status是存数据的，而并不是通过status来控制增删改查。所以不大理解这样做的初衷，是不是咱这快逻辑有什么特殊考虑。
> 
> 通过deletetime来控制是否删除，剩下的都是update操作，不一定是只当做CRD的操作，也可以操作其他资源什么的，只是判断的标准是当前CRD的meta的数据而已。你之前说“用户将资源状态改为ClusterTerminating后” 为什么不是用户执行“kubectl delete cluster xxxx”这样来控制的？

status这里你的理解跟我理解一样，这里我们用status控制是历史遗留问题，目前也没有经历把status里面的控制放到spec里面进行控制

**Comment by cuisongliu** [comment]
那我明白了，多谢解答，^_^
