### ISSUE TITLE
v1.8.0 install error "15.Install tke-auth-api [Failed] [600.130850s] error timed out waiting for the condition"

### ISSUE THREAD

**Issue by dazsco** [tkestack/tke#1705]
**What happened**:

2021-12-09 06:35:50.600	info	tke-installer	15.Install tke-auth-api doing
2021-12-09 06:45:50.731	error	tke-installer	15.Install tke-auth-api [Failed] [600.130850s] error timed out waiting for the condition
2021-12-09 06:46:00.600	info	tke-installer	15.Install tke-auth-api doing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
this may be your env not ready to deploy k8s work load. pleas check your network and make sure all pod in your target cluster is running

**Comment by dazsco** [comment]
but I strictly follow the installation of the document, including the environment preparation of all servers.

**Comment by leoryu** [comment]
please check your pod status in your global cluster. if failed, please give the failed message

**Comment by dazsco** [comment]
[root@tke-82-global ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS              RESTARTS   AGE
kube-system   coredns-6c654f5cc6-dcpt4                 0/1     ContainerCreating   0          22m
kube-system   coredns-6c654f5cc6-psddl                 0/1     ContainerCreating   0          22m
kube-system   etcd-10.10.10.81                         1/1     Running             0          19m
kube-system   etcd-10.10.10.82                         1/1     Running             0          19m
kube-system   etcd-10.10.10.83                         1/1     Running             0          19m
kube-system   flannel-2qkhs                            0/1     CrashLoopBackOff    9          22m
kube-system   flannel-rr4v6                            0/1     CrashLoopBackOff    9          21m
kube-system   flannel-sk8dh                            0/1     CrashLoopBackOff    9          21m
kube-system   galaxy-daemonset-25k2x                   1/1     Running             3          21m
kube-system   galaxy-daemonset-hkmrs                   1/1     Running             1          21m
kube-system   galaxy-daemonset-zrb6c                   1/1     Running             0          22m
kube-system   keepalived-10.10.10.81                   1/1     Running             0          21m
kube-system   keepalived-10.10.10.82                   1/1     Running             0          20m
kube-system   keepalived-10.10.10.83                   1/1     Running             0          20m
kube-system   kube-apiserver-10.10.10.81               1/1     Running             0          20m
kube-system   kube-apiserver-10.10.10.82               1/1     Running             0          20m
kube-system   kube-apiserver-10.10.10.83               1/1     Running             0          19m
kube-system   kube-controller-manager-10.10.10.81      1/1     Running             0          19m
kube-system   kube-controller-manager-10.10.10.82      1/1     Running             0          19m
kube-system   kube-controller-manager-10.10.10.83      1/1     Running             0          19m
kube-system   kube-proxy-9cl7t                         1/1     Running             0          22m
kube-system   kube-proxy-fbrfr                         1/1     Running             0          21m
kube-system   kube-proxy-rd2cj                         1/1     Running             0          21m
kube-system   kube-scheduler-10.10.10.81               1/1     Running             0          19m
kube-system   kube-scheduler-10.10.10.82               1/1     Running             0          19m
kube-system   kube-scheduler-10.10.10.83               1/1     Running             0          19m
kube-system   metrics-server-v0.3.6-59c66b5dfd-fwt6v   0/2     ContainerCreating   0          20m
tke           tke-auth-api-6fcfdb454d-592rb            0/1     ContainerCreating   0          18m
tke           tke-auth-api-6fcfdb454d-qp8xh            0/1     ContainerCreating   0          18m

**Comment by dazsco** [comment]
![image](https://user-images.githubusercontent.com/30418809/145364250-048b723e-92d9-4970-a7bd-4918ce5bdb51.png)

**Comment by dazsco** [comment]
I think I know what's going on. The network card name is "eth0" by default during installation, but it is "ens192" on my server. I am trying to install again.
