### ISSUE TITLE
v1.8 策略管理功能报错，浏览器卡死。

### ISSUE THREAD

**Issue by dazsco** [tkestack/tke#1709]
![image](https://user-images.githubusercontent.com/30418809/145507979-9f1eb5e2-7486-4213-bb38-b1473439a59d.png)

通过开发人员工具跟踪发现该页面会轮询搜索，搜索的时候如无内容就回报这个错误
![image](https://user-images.githubusercontent.com/30418809/145508085-c904cfc3-8026-48fd-a5db-2a1b0fc95586.png)

输入搜索关键词后搜索后同样会一直轮询
![image](https://user-images.githubusercontent.com/30418809/145508288-c9595fa2-98b9-479c-9ad5-6101c0238d37.png)

**Comment by dazsco** [comment]
点击 新建 的时候弹出模态框无法操作，浏览器直接卡死。 @leoryu

**Comment by leoryu** [comment]
duplicate https://github.com/tkestack/tke/issues/1634
