### ISSUE TITLE
the user cannot be deleted normally. 

### ISSUE THREAD

**Issue by dazsco** [tkestack/tke#1710]
**What happened**:

![image](https://user-images.githubusercontent.com/30418809/145509793-715351d6-274d-45e5-b609-7cca3134cc6b.png)

how do I upgrade the system, I did not see the relevant content in the document. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: v1.8.0
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by dazsco** [comment]
@leoryu 
hello brother, I cannot successfully delete the user on the console, as shown in the figure above.
Please also ask, I want to upgrade to the v1.8.1 version, but follow the method of "https://github.com/tkestack/tke/tree/master/cmd/tke-upgrade" and run the command "./cmd/tke" -upgrade/upgrate.sh" after waiting indefinitely, there is a typo in the document, the file name is upgrade.
  In the installation instructions of the latest version release v1.8.1, version=v1.8.0 instead of 1.8.1, is it a writing error? 
![image](https://user-images.githubusercontent.com/30418809/145771894-c5f172d7-950f-4b76-9fb3-cc02b98e2bdd.png)

**Comment by leoryu** [comment]
for upgrade please check https://github.com/tkestack/tke#upgrade

**Comment by leoryu** [comment]
> @leoryu hello brother, I cannot successfully delete the user on the console, as shown in the figure above. Please also ask, I want to upgrade to the v1.8.1 version, but follow the method of "https://github.com/tkestack/tke/tree/master/cmd/tke-upgrade" and run the command "./cmd/tke" -upgrade/upgrate.sh" after waiting indefinitely, there is a typo in the document, the file name is upgrade. In the installation instructions of the latest version release v1.8.1, version=v1.8.0 instead of 1.8.1, is it a writing error? ![image](https://user-images.githubusercontent.com/30418809/145771894-c5f172d7-950f-4b76-9fb3-cc02b98e2bdd.png)

Thanks for your remind, I have correct the installer version in release notes.

**Comment by dazsco** [comment]
thks
