### ISSUE TITLE
直接调用api不能访问

### ISSUE THREAD

**Issue by papandadj** [tkestack/tke#1748]
在该文档里面 https://tkestack.github.io/docs/develop/api.html 创建访问凭证后调用接口报错
![image](https://user-images.githubusercontent.com/25424898/150284461-112e644d-d6ab-428b-b520-190c09ce87b9.png)

如果取消前缀platform, 报错401
![image](https://user-images.githubusercontent.com/25424898/150284571-809fa3bb-7d32-4448-baa0-30392acf164f.png)

但是运行结果在 ”ACP+ 全栈云原生开放平台“（该产品好像是收费的） 是可以执行成功的。

**Comment by leoryu** [comment]
If you access your api out of cluster, you should set cookie in your request header. You can use `f12` to check headers when you access tkestack through browser.
