### ISSUE TITLE
策略界面冻结

### ISSUE THREAD

**Issue by xiaoping378** [tkestack/tke#1757]
![image](https://user-images.githubusercontent.com/5623173/151527105-718c9fc5-9e65-44c9-83a6-e959c528534e.png)

**What happened**:
平台管理员角色，点击新建策略，界面冻结。
**What you expected to happen**:
可以新建
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.81
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
duplicate https://github.com/tkestack/tke/issues/1634
