### ISSUE TITLE
tke安装报错

### ISSUE THREAD

**Issue by LanXHH** [tkestack/tke#1784]
基础信息
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

# uname  -r 
3.10.0-693.el7.x86_64

# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:85:1f:ec brd ff:ff:ff:ff:ff:ff
    inet 10.83.12.21/22 brd 10.83.15.255 scope global ens192
       valid_lft forever preferred_lft forever
[root@szzb-tke-dev-instller-01 ~]# 

安装报错
##清理
# curl -s https://tke-release-1251707795.cos.ap-guangzhou.myqcloud.com/tools/clean.sh | sh

##执行安装
# arch=amd64 version=v1.8.1  && sha256sum --check --status tke-installer-linux-$arch-$version.run.sha256 && chmod +x tke-installer-linux-$arch-$version.run && ./tke-installer-linux-$arch-$version.run

Step.1 preflight
root: yes
check docker status
available disk space(/opt):  100 GiB
available disk space(/var/lib):  88 GiB
Step.2 check containerd status
containerd status is not running
install containerd [in process]
etc/
etc/systemd/
etc/systemd/system/
etc/systemd/system/containerd.service
etc/crictl.yaml
usr/
usr/local/
usr/local/sbin/
usr/local/sbin/runc
usr/local/bin/
usr/local/bin/ctr
usr/local/bin/containerd-shim
usr/local/bin/containerd
usr/local/bin/containerd-stress
usr/local/bin/critest
usr/local/bin/containerd-shim-runc-v2
usr/local/bin/crictl
usr/local/bin/ctd-decoder
usr/local/bin/containerd-shim-runc-v1
nerdctl
containerd-rootless-setuptool.sh
containerd-rootless.sh
install containerd [done]
Step.3 load tke-installer image [in process]
unpacking docker.io/tkestack/tke-installer-amd64:v1.8.1 (sha256:b2dd5db0379e466375551a4abd41b8a5098e4f61b313a72958a782a479a94fbc)...done
unpacking overlayfs@sha256:b2dd5db0379e466375551a4abd41b8a5098e4f61b313a72958a782a479a94fbc (sha256:b2dd5db0379e466375551a4abd41b8a5098e4f61b313a72958a782a479a94fbc)...done
unpacking docker.io/tkestack/registry-amd64:2.7.1 (sha256:4589b6631d617e55ee0f1af3ee1b5b6765fabce4b54a7e851ffb526aa27d51cc)...done
unpacking overlayfs@sha256:4589b6631d617e55ee0f1af3ee1b5b6765fabce4b54a7e851ffb526aa27d51cc (sha256:4589b6631d617e55ee0f1af3ee1b5b6765fabce4b54a7e851ffb526aa27d51cc)...done
Step.3 load tke-installer image [done]
Step.4 clean old data [in process]
Step.4 clean old data [done]
Step.5 start tke-installer [in process]
0ef059d8dd4d03067f1d2d219a274e74226679616ee93401e93db927e81a2242
Step.5 start tke-installer [done]
Step.6 start regisry [in process]
000d55172585a6cca02c4ead5dccff2cceeecc9ac35669b3de348f824f5ec51b
dec70d0ed42cd19946495dc3d9d81f253837898b3c5ae0244b1bb8085b77120d
Step.6 start registry [done]
Step.6 check tke-installer status [in process]
Step.6 retries left 9
Step.6 check tke-installer status [in process]
Step.6 retries left 8
Step.6 check tke-installer status [in process]
Step.6 retries left 7
Step.6 check tke-installer status [in process]
Step.6 retries left 6
Step.6 check tke-installer status [in process]
Step.6 retries left 5
Step.6 check tke-installer status [in process]
Step.6 retries left 4
Step.6 check tke-installer status [in process]
Step.6 retries left 3
Step.6 check tke-installer status [in process]
Step.6 retries left 2
Step.6 check tke-installer status [in process]
Step.6 retries left 1
Step.6 check tke-installer status [in process]
Step.6 retries left 0
check installer status error
/app/run.sh: line 28: ./bin/tke-installer: not found
Failed to start my_second_process: 127
/app/run.sh: line 28: ./bin/tke-installer: not found
Failed to start my_second_process: 127
/app/run.sh: line 28: ./bin/tke-installer: not found
Failed to start my_second_process: 127
/app/run.sh: line 28: ./bin/tke-installer: not found
Failed to start my_second_process: 127
[FAIL] Operation failed.

**Comment by leoryu** [comment]
Maybe your image corrupted, you can delete your image through `nerdctl` and re-run tke-installer.
