### ISSUE TITLE
failed to start daemon: Error initializing network controller

### ISSUE THREAD

**Issue by wl-chen** [tkestack/tke#1802]
**What happened**:

docker daemon in tke-installer start failed
logs:
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: modprobe: can't change directory to '/lib/modules': No such file or directory
 iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
 Perhaps iptables or your kernel needs to be upgraded.
  (exit status 3)

**What you expected to happen**:

docker daemon in tke-installer start successfully

**How to reproduce it (as minimally and precisely as possible)**:

im not for sure

**Anything else we need to know?**:

**Environment**:
- TKE version: c2cfc9592ba222c41790841b57fadb9fa72b6d0c
- Global or business cluster: global
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-tke.2", GitCommit:"7b9cf6e45068a2fc824cafe529c1f5271d201fcd", GitTreeState:"clean", BuildDate:"2022-03-03T11:51:31Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-tke.2", GitCommit:"7b9cf6e45068a2fc824cafe529c1f5271d201fcd", GitTreeState:"clean", BuildDate:"2022-03-15T03:40:30Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
- Install addons:
- Others:
system image version: 
TencentOS Server 3.1 (TK4)
镜像ID：img-eb30mz89

**Comment by huxiaoliang** [comment]
related referance:
