### ISSUE TITLE
StatefulSet pod展示在了deployment pod 列表中

### ISSUE THREAD

**Issue by JiaYongfei** [tkestack/tke#1806]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: v1.19
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by jo-hnny** [comment]
原有请求方式：api/v1/namespaces/testns/pods?limit=20&labelSelector=k8s-app=test,qcloud-app=test&fieldSelector=

修复方式： api/v1/namespaces/testns/deployment/test/pods?limit=20
