### ISSUE TITLE
1.9.0 部署成功了， 新建立集群或者新加入节点，报错

### ISSUE THREAD

**Issue by khw934** [tkestack/tke#1826]
![image](https://user-images.githubusercontent.com/35864027/161883880-5e60d1a0-bb38-4a81-9ee6-13ed6fcb4881.png)

用户名和密码都是对的

背景： 通过 tke-install 把tke 安装到 192.168.1.176， 目前新建个独立集群 192.168.1.177 ，在界面操作报错
通过在 192.168.1.177 抓包如下：

![image](https://user-images.githubusercontent.com/35864027/163532401-0cfdbbea-28c1-47e7-bcb5-30a042bcc004.png)

在 global 节点抓包如下

![image](https://user-images.githubusercontent.com/35864027/163532566-319af0dc-cb3f-4871-b376-798b5380575a.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:  1.9.0
- Global or business cluster: Global 
- Kubernetes version (use `kubectl version`):   v1.21.4-tke.3
- Install addons: 
- Others:

**Comment by aiaiduo** [comment]
我也遇到了这个问题，大佬这个问题解决了么？

**Comment by lhd311** [comment]
怎么解决的呢？
