### ISSUE TITLE
安装失败：tke-business-controller 模块超时

### ISSUE THREAD

**Issue by Duan112358** [tkestack/tke#206]
**What happened**:

tke-business-controller 模块安装超时

**What you expected to happen**:
正常安装
**How to reproduce it (as minimally and precisely as possible)**:
勾选 business 模块
**Anything else we need to know?**:

**Environment**: 
- OS: centos-7.6
- TKE version: 1.2.0
- Global or business cluster: global
- Kubernetes version (use `kubectl version`): 1.6
- Install addons: business
- Others: 腾讯云主机，北京 3 区

```
2020/03/24 03:47:24 17.Install tke-registry-api doing
2020/03/24 03:47:39 17.Install tke-registry-api [Success] [15.034904s]
2020/03/24 03:47:39 18.Install tke-business-api doing
2020/03/24 03:47:54 18.Install tke-business-api [Success] [15.026088s]
2020/03/24 03:47:54 19.Install tke-business-controller doing
2020/03/24 03:57:54 19.Install tke-business-controller [Failed] [600.022252s] error timed out waiting for the condition

```

**Comment by Duan112358** [comment]
关闭 business 模块后，monitor 模块也是同样问题，超时失败

![image](https://user-images.githubusercontent.com/1957818/77387208-ba50d300-6dc7-11ea-9c69-a2a6312f86eb.png)

**Comment by ruyingzhe** [comment]
pls check if the node specifications is larger than 8c16g

**Comment by Duan112358** [comment]
![image](https://user-images.githubusercontent.com/1957818/77555344-1d3e8900-6ef2-11ea-85b7-b69d2a4042aa.png)
原来的是 **4c8g** , 剔除 business 和 monitor 也能安装成功
升级成 **8c6g** 这俩模块也能成功了
感谢～
