### ISSUE TITLE
镜像资源路径 tkestack 和 library 交叉 Bug

### ISSUE THREAD

**Issue by Duan112358** [tkestack/tke#212]
以内置镜像：registry.tke.com 为例

**What happened**:

创建「独立集群」或者添加「扩展」后，节点镜像出现 ``imagePullBackOff`` 问题

**What you expected to happen**:

* registry.tke.com/**tkestack**/xxx
* registry.tke.com/**library**/xxx

> 以上两个路径中资源有穿插，请确保资源路径一致

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2
- Global or business cluster: global & business
- Kubernetes version (use `kubectl version`): 1.6
- Install addons: prometheus
- Others:

**临时解决办法**

复制一份异常镜像，重新 push, 举个例子

```
docker tag registry.tke.com/library/alertmanager:v0.18.0  registry.tke.com/tkestack/alertmanager:v0.18.0
docker push registry.tke.com/tkestack/alertmanager:v0.18.0
```
稍等片刻，节点恢复正常

**Comment by QianChenglong** [comment]
Fixed
