### ISSUE TITLE
17.Install tke-registry-api [Failed] [600.058036s] error timed out waiting for the condition

### ISSUE THREAD

**Issue by dacuotecuo** [tkestack/tke#2250]
**What happened**: 17.Install tke-registry-api [Failed] [600.058036s] error timed out waiting for the condition

**What you expected to happen**:
安装tke时一直卡在17步，提示的错误如上

 通过master节点看到如下内容：
kubectl get pods -A 
--------------------------------------------------------------------------------------                                         
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   coredns-5f56b5b689-8kgss                 1/1     Running            0          100m
kube-system   coredns-5f56b5b689-bszr5                 1/1     Running            0          100m
kube-system   etcd-9.135.228.204                       1/1     Running            0          100m
kube-system   flannel-kd47b                            1/1     Running            0          100m
kube-system   galaxy-daemonset-dl2hk                   1/1     Running            0          100m
kube-system   kube-apiserver-9.135.228.204             1/1     Running            0          101m
kube-system   kube-controller-manager-9.135.228.204    1/1     Running            0          100m
kube-system   kube-proxy-5j4md                         1/1     Running            0          100m
kube-system   kube-scheduler-9.135.228.204             1/1     Running            0          99m
kube-system   metrics-server-v0.3.6-75988d7fb4-z9vjl   2/2     Running            0          100m
tke           tke-registry-api-84cc4f6db8-jbq89        0/1     CrashLoopBackOff   23         79m
tke           tke-registry-api-84cc4f6db8-rcz9f        0/1     CrashLoopBackOff   24         79m

-------------------------------------------
查看api的这个pod的错误日志，内容如下：
kubectl logs tke-registry-api-84cc4f6db8-rcz9f -n tke
-----------------
2023-03-21 08:04:47.810 INFO    Initializing cache sizes based on 100MB limit
W0321 08:05:09.246223       1 clientconn.go:1326] [core] grpc: addrConn.createTransport failed to connect to {etcd.kube-system:2379 etcd.kube-system <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout". Reconnecting...
2023-03-21 08:05:18.244 ERROR   Failed to initializing oidc authenticator       {"error": "Get \"https://tke-auth-api/oidc/.well-known/openid-configuration\": context deadline exceeded"}
Error: invalid authentication config: Get "https://tke-auth-api/oidc/.well-known/openid-configuration": context deadline exceeded

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.9.0
- Global or business cluster: 
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-tke.3", GitCommit:"7b9cf6e45068a2fc824cafe529c1f5271d201fcd", GitTreeState:"clean", BuildDate:"2022-03-25T11:07:06Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.4-tke.3", GitCommit:"7b9cf6e45068a2fc824cafe529c1f5271d201fcd", GitTreeState:"clean", BuildDate:"2022-03-25T11:04:32Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
- Install addons:
- Others:

**Comment by leoryu** [comment]
this should be resolved in latest code

**Comment by dacuotecuo** [comment]
> this should be resolved in latest code

tks
