### ISSUE TITLE
更改镜像仓库域名后，“镜像上传指引”中未同步

### ISSUE THREAD

**Issue by tzrd** [tkestack/tke#2251]
**What happened**:
1）打开 “集群管理“-“TKE”-“配置管理”-"ConfigMap", “命名空间”-“tke”, 选择 “tke-registry-controller”
2）编辑 “YAML”，更改 “domainSuffix”
3）打开 “组织资源”-“镜像仓库管理”，“新建” 命名空间
4）点击进入 新建的命名空间，打开“镜像上传指引”中的default.registry.xxx.xxx没有更新为更改的域名

**What you expected to happen**:
“镜像上传指引”中的default.registry.xxx.xxx变为更新后的

**How to reproduce it (as minimally and precisely as possible)**:
参考“**What happened**”内容

**Anything else we need to know?**:
没有

**Environment**: prod
- TKE version: 1.9.0
- Global or business cluster: Global 
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by leoryu** [comment]
At present we doesn't support modify registry domain after installed
