### ISSUE TITLE
在有 3 个 gpu 的节点出现调度失败的情况

### ISSUE THREAD

**Issue by scxu** [tkestack/tke#226]
**What happened**:

想要实现 https://ieeexplore.ieee.org/abstract/document/8672318 这边文章中的内容。部署成功后发现其中一台有四卡的节点调度是没有问题的，但是另外一台只有**三卡**的机器会出现 `Pending` 的情况，也就是明明有资源但是 scheduler 说：

```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 Insufficient tencent.com/vcuda-core, 3 node(s) didn't match node selector.
```

这里是 `kubectl describe node` 的结果：

![image](https://user-images.githubusercontent.com/27944120/77897920-e929e600-72ac-11ea-871a-cd1d554fa8a8.png)

![image](https://user-images.githubusercontent.com/27944120/77899750-97cf2600-72af-11ea-8fa8-6ff0b1a6cd7d.png)

可以看到是只有两块卡被调度了。

之所以是有三块卡是因为有一块卡出了问题，把它屏蔽了。然后这种调度失败可以通过强制 `kube-scheduler` 重启的方式一定程度上解决，重启之后一般会正常一下，但是后面还会出类似的问题。

在有三块卡的机器上执行 `nvidia-smi topo -mp` 结果如下：

```
	GPU0	GPU1	GPU2	CPU Affinity
GPU0	 X 	SYS	SYS	0-11
GPU1	SYS	 X 	PIX	0-11
GPU2	SYS	PIX	 X 	0-11

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
```

- k8s 版本：1.17.3
- nvidia driver 版本：440.59

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by kevinfeng** [comment]
抱歉回复的有点迟，pod申请的vcore和vmemory是多少呢？

**Comment by scxu** [comment]
感谢回复，我看了一下，申请的是这样子的：

```
tencent.com/vcuda-core:    100
tencent.com/vcuda-memory:  1
```

**Comment by kevinfeng** [comment]
集群中是有4个节点，其中一个是3卡，一个是4卡，另外两个没有GPU，是这样的吗？

**Comment by scxu** [comment]
整个集群是四台机器，都是有 GPU 的，只有一台是 3 卡的，其他都是 4 卡

**Comment by scxu** [comment]
你好，请问还需要其他的信息吗

**Comment by kevinfeng** [comment]
这里是gpu-adminssion这个组件有点问题：调度的时候这个组件会在schedule的filter阶段给pod添加annotation，这个动作会触发pod更新event，导致scheduler重复处理这个pod的调度，有些情况下会导致scheduler本地的调度cache和实际不一致。这里涉及到scheduler的内部流程，还不太好解决

**Comment by scxu** [comment]
那请问是我猜测的只在奇数卡时会出现的问题吗？

**Comment by kevinfeng** [comment]
我没有在1.17上测试过，不过从原理上看应该和奇数偶数没关系；对调度器来说，它看到的是300个vcore还是400个vcore应该没有差别

**Comment by scxu** [comment]
我可以通过对 gpu-admission 做修改来解决这个问题吗？主要是我还没做做过这部分的工作，有点小懵

**Comment by kevinfeng** [comment]
修改的话，需要把gpu-admission里在filter阶段做的事情，后移到bind阶段； 选出机器以后，直接bind；阿里的GPUshare是这么做的：https://github.com/AliyunContainerService/gpushare-scheduler-extender/blob/master/pkg/cache/nodeinfo.go

**Comment by scxu** [comment]
能更具体点吗...我也是第一次做这部分工作 T_T

**Comment by kevinfeng** [comment]
gpu-admission就是一个调度器插件，调度器有几个阶段filter bind之类的；目前是在filter阶段去选择node，然后让调度器自己去bind，这种情况有可能pending；如果把之前做的事情，后移到bind阶段，就一定可以把pod指定到一个机器上，不会pending；   关于调度器插件网上很多文章介绍，稍微看下就能明白

**Comment by scxu** [comment]
> 这里是gpu-adminssion这个组件有点问题：调度的时候这个组件会在schedule的filter阶段给pod添加annotation，这个动作会触发pod更新event，导致scheduler重复处理这个pod的调度，有些情况下会导致scheduler本地的调度cache和实际不一致。这里涉及到scheduler的内部流程，还不太好解决

https://github.com/tkestack/gpu-admission/blob/36c722ff6b8e7897f3e4f8d3f2cc4e103ef54c3e/pkg/predicate/gpu_predicate.go#L334

是不是这里的问题导致的重复调度呢？那是不是我把这部分挪到 bind 阶段就能解决问题呢？
