### ISSUE TITLE
1.7.1版本的tke，在使用1年后，管理集群出现x509的相关错误，无法连接创建的集群，且无法更新证书。

### ISSUE THREAD

**Issue by zhangshangbj** [tkestack/tke#2260]
1、无法修改证书信息：
![image](https://user-images.githubusercontent.com/31945209/232397629-be94d76d-a8cb-420f-aee1-2bdbc43ae897.png)

2、tke页面完全无法操作，点击集群就会出现以下报错：
![image](https://user-images.githubusercontent.com/31945209/232398151-0f833bc7-7ec1-4879-9c0d-cc6a2576787c.png)

请问如何处理该故障。

**Comment by leoryu** [comment]
https://github.com/tkestack/tke/blob/master/docs/guide/zh-CN/best-practices/renewing-kubernetes-certificates.md
Please check this.
