### ISSUE TITLE
How to create a new tenant

### ISSUE THREAD

**Issue by lkxjtu** [tkestack/tke#2265]
**What would you like to be added**:

How to create a new tenant

**Why is this needed**:

Most tkestack resources support TenantID field, which can be used to filter resources of this tenant. But the TenantID field  value is always "default". How can I used TenantID for tenant isolation? And how to create a new tenant in tkestack?

**Comment by leoryu** [comment]
https://tkestack.github.io/web/zh/blog/2022/01/04/tkestack-ldap/
Please check this blog.
