### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by web3creator** [tkestack/tke#2303]
**What happened**:

http://console.tke.com/ 
<img width="1152" alt="截屏2023-07-10 12 47 09" src="https://github.com/tkestack/tke/assets/52997135/3f52f87d-cc9b-436c-82f0-31d238da07be">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: amd1.9.2
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by iamlinix** [comment]
I'm having this issue with 1.9.2, please share a link to the fix PR

and is there any workaround to make the web work?

 @web3creator

**Comment by guofengtd** [comment]
![image](https://github.com/tkestack/tke/assets/13635167/fd2935f8-126f-4b0b-9b39-4b4a6e924fd3)

the same, any suggestion?

**Comment by hahahaaaaa** [comment]
kubectl -n tke edit ingress gateway

Change 'registry.tke.com' to "*. tke. com", save and exit the generic domain name
The configuration of ingress is missing the console domain configuration
