### ISSUE TITLE
User can set master node as schedulable when creating cluster in API

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#248]
User can set master node as schedulable when creating cluster

Master node configuration is supported to be schedulable, and some users use master nodes to run workloads

**Comment by QianChenglong** [comment]
![image](https://user-images.githubusercontent.com/1881126/78962520-e8a01380-7b26-11ea-9b7c-e742d10d1000.png)

![image](https://user-images.githubusercontent.com/1881126/78962461-c1e1dd00-7b26-11ea-9a74-904dfdbf4fa1.png)

**Comment by QianChenglong** [comment]
Support in https://github.com/tkestack/tke/commit/af5e10569ee5a6e258433d8accaca213b4fe3b11
