### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by Zephery** [tkestack/tke#25]
Hello

**What would you like to be added**:
Could you plz upload your monitor.json and notify.json for running locally?

And Can you give me your contact information? Like wechat group

**Why is this needed**:

**Comment by choujimmy** [comment]
The startup configuration of `monitor-api` and `notify-api` is similar to other apiserver components. You can use the `tke-monitor-api -h` or `tke-notify-api -h` command to view all command line parameters after compilation is complete.
Next week we will update this document with this configuration.

**Comment by Zephery** [comment]
Please update this document with this configuration. 
Thank you~
