### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by cn-ygf** [tkestack/tke#261]
一些个人小建议，勿喷.
1、完善配置
很多功能还需要手写yaml进行配置，比如ingress
2、添加应用模板功能
把一些常用的应用可以保存成一个模板，然后一键部署，
比如一键部署mysql，mysql主从，一键部署网站加数据库之类的模板

**Comment by ruyingzhe** [comment]
These features are planned for Q2 development, so pls look forward to our releases
