### ISSUE TITLE
Build error on ‘make release’

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#28]
**Describe the bug**

When using the `make release` command to build the installer,  errors occurred like below.

```log
===========> Pushing tke-platform-api c72b21f image to tkestack
The push refers to repository [docker.io/tkestack/tke-platform-api]
675b40083459: Preparing
83b390cc87eb: Preparing
6132d92de499: Preparing
77cae8ab23bf: Preparing
denied: requested access to the resource is denied
make[2]: *** [image.push.tke-platform-api] Error 1
make[2]: Leaving directory `/root/gopath/src/tkestack.io/tke'
make[1]: *** [push] Error 2
make[1]: Leaving directory `/root/gopath/src/tkestack.io/tke'
make: *** [release] Error 2
```

Since I don’t have the permission of tkestack repo in dockerhub, I can’t build the tke-installer image for now.

Hope tkestack support releasing image repos other than `tkestack/*`,  user can customize their own repository

**Environment**
 - OS: Linux VM_149_11_centos 3.10.107-1-tlinux2_kvm_guest-0049 # 1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - golang: go version go1.12.4 linux/amd64

**Comment by QianChenglong** [comment]
Change release.The build artifact is only one file.
