### ISSUE TITLE
namespace in business management view has poor readability

### ISSUE THREAD

**Issue by jianzzz** [tkestack/tke#319]
**What happened**:
In business management view, when I select a namespace, it alway shows metadata.name, not spec.namespace. I think it has poor readability.

**Environment**:
- TKE version: v1.2.3

**Comment by jianzzz** [comment]
correct: I think the best eay is spec.clusterDisplayName/spec.namespace, cause we may use same-name namespace.

**Comment by ruyingzhe** [comment]
The namespace page in business view already shows the cluster name which the ns belong. People can distinguish ns even they have same name but under different cluster.
