### ISSUE TITLE
cluster host in non-ip formart is not correctly handled

### ISSUE THREAD

**Issue by langyenan** [tkestack/tke#363]
**What happened**:
I'm trying to import a cluster, the address of  the kube-apiserver is `https://proxy.com/cluster/xxxx`, it never succeeded. The error returned is  `the server could not find the requested resource`

I dug into the code, the function `ClusterHost` always append the `port` after `host`, when the host is an url like `proxy.com/cluster/xxxx`, this function returned `proxy.com/cluster/xxxx:443`, rather than `proxy.com:443/cluster/xxxx`

https://github.com/tkestack/tke/blob/35e0a5f3c62396cd00a3d0a918c5bb68a3fa6184/pkg/platform/util/client.go#L551
  
**What you expected to happen**:
if the host is in format of `domain/path`, the `ClusterHost` should return `domain:port/path`, rather than `domain/path:port`

**Comment by QianChenglong** [comment]
Support in release-1.2 and later will merge to master
