### ISSUE TITLE
tke-installer-v0.15.0 doesn't contain local-tcr and kubernetes images?

### ISSUE THREAD

**Issue by binji-li** [tkestack/tke#38]
tke-installer-v0.15.0 doesn't contain local-tcr and kubernetes images, so I need to download these images manually.

installer log: 
v0.1: digest: sha256:cc153f2ed523952e85a73fafaff87d05fb14fb7e068ef330fb671274c4ed5998 size: 734
2019/12/04 08:08:38 upload registry.tke.com/library/configmap-reload:v0.1 to registry success[46/46]
2019/12/04 08:08:38 3.Push images to registry.tke.com/library [Success] [2.350667s]

docker images:
\# docker images | grep kube
tkestack/kube-state-metrics                           v1.6.0              87970984231a        6 months ago        230MB
registry.tke.com/library/kube-state-metrics           v1.6.0              87970984231a        6 months ago        230MB
\# docker images | grep registry.tke.com | wc -l
46
\# docker images | grep registry.tke.com | grep kube
registry.tke.com/library/kube-state-metrics           v1.6.0              87970984231a        6 months ago        230MB

**Comment by QianChenglong** [comment]
New version fix, wait release.
