### ISSUE TITLE
Docker root path, registry, http_proxy for docker in Global cluster

### ISSUE THREAD

**Issue by binji-li** [tkestack/tke#39]
Could you please add _Docker Root Dir_, _registry_(already configure registry.tke.com, but don't work in docker daemon.json) and _http_proxy_ configuration of the Global cluster on installer web page? Otherwise, after docker installed, its root dir is /var/lib/docker and its registry is docker.io and my network cannot connect to docker.io,

# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.107-1-tlinux2-0046
Operating System: Tencent tlinux 2.2 (Final)
OSType: linux
Architecture: x86_64
CPUs: 80
Total Memory: 125.3GiB
Name: TENCENT64.site
ID: AVWD:B3RY:H7V6:2L3D:VUZO:PJ6M:E4B3:SEC2:5DQR:SRLJ:UM75:7KSN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker.io/
Live Restore Enabled: true
Product License: Community Engine

**Comment by binji-li** [comment]
images in local registry.tke.com are under registry.tke.com/library/, and global master node installation pulls from docker.io/tkestack/

**Comment by binji-li** [comment]
installer:
[root@TENCENT64 /data]# docker images | grep registry.tke.com | grep tke-
registry.tke.com/library/tke-installer                v0.15.2             4572c821ecee        33 minutes ago      3.25GB
registry.tke.com/library/tke-installer                v0.15.1             60871f36c6d8        23 hours ago        3.25GB
registry.tke.com/library/tke-installer                v0.15.0             c39f8ad60fcb        3 days ago          3.19GB
registry.tke.com/library/tke-auth                     v0.15.0             22fab403c198        3 days ago          70.5MB
registry.tke.com/library/tke-business-controller      v0.15.0             231a7e5d6537        3 days ago          64.9MB
registry.tke.com/library/tke-business-api             v0.15.0             3801811cc216        3 days ago          71.9MB
registry.tke.com/library/tke-notify-controller        v0.15.0             00b70289f2a2        3 days ago          61.6MB
registry.tke.com/library/tke-gateway                  v0.15.0             511ac6fc1bdb        3 days ago          77.8MB
registry.tke.com/library/tke-notify-api               v0.15.0             ee9ab6bc3544        3 days ago          70.8MB
registry.tke.com/library/tke-registry-api             v0.15.0             41863b5feea1        3 days ago          78.2MB
registry.tke.com/library/tke-monitor-controller       v0.15.0             580a5f431cfa        3 days ago          64.2MB
registry.tke.com/library/tke-platform-controller      v0.15.0             c1d7beac4195        3 days ago          71.2MB
registry.tke.com/library/tke-monitor-api              v0.15.0             721792004e1d        3 days ago          74.5MB
registry.tke.com/library/tke-platform-api             v0.15.0             d852dc770c02        3 days ago          79.1MB
registry.tke.com/library/tke-event-watcher            v0.1                8df73ccfd0dc        12 months ago       782MB
registry.tke.com/library/tke-audit-collector          v0.3                24c21845c255        13 months ago       235MB

global master node:
tke           tke-auth-69d5d57cc7-2r7b4             0/1     ImagePullBackOff   0          3m17s
tke           tke-auth-69d5d57cc7-b84sv             0/1     ImagePullBackOff   0          3m17s

**Comment by QianChenglong** [comment]
New version had fix

**Comment by Jack47** [comment]
maybe add fixed commit id would be better?  @QianChenglong
