### ISSUE TITLE
Wrong error message when installing TKE installer

### ISSUE THREAD

**Issue by ryanqin01** [tkestack/tke#407]
**What happened**:
When installing TKE installer, it will report error like "No such container: tke-installer".
And in the end, it will report [FAIL] Operation failed.
But in fact, it is intalled successfully.
TKE installer should wait when installing tke-installer is slow, instead of reporting confusing error message.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2.4
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by QianChenglong** [comment]
Thans for your feedback! 
Fixed soon.
