### ISSUE TITLE
Installing TKE takes too much time

### ISSUE THREAD

**Issue by ryanqin01** [tkestack/tke#408]
**What happened**:
![image](https://user-images.githubusercontent.com/15393045/83243478-867f9880-a1d0-11ea-9298-f4d9b6853d0e.png)

It took me 27 hours to install TKE.
I found that, many steps take about 25 minutes. I suspect there is a task took too much time in these steps.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2.4
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by QianChenglong** [comment]
Generally, the installation can be completed in tens of minutes. Please provide your environment and installation logs to see where it takes more time.

**Comment by ryanqin01** [comment]
The tke.log and environment is provided.

# cat /proc/version
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:              7
CPU MHz:               2300.000
BogoMIPS:              4600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
[tke.log](https://github.com/tkestack/tke/files/4705107/tke.log)

**Comment by QianChenglong** [comment]
![image](https://user-images.githubusercontent.com/1881126/83320011-c482c800-a275-11ea-8917-44d57963ca4c.png)
Please check your network band from install node to your global node.

**Comment by Shangru-WU** [comment]
Thanks for providing the log. This happened because your DNS resolver did not work. We had find a way to work around it (#87e983e5). 

Release in next version.
