### ISSUE TITLE
gpu-manger are always scheduled to master node

### ISSUE THREAD

**Issue by ryanqin01** [tkestack/tke#409]
**What happened**:
I use two GPU machines to deploy a k8s cluster using TKE. One as master node and one as worker node. When I try to install gpu manger plugin, it will always fail. Since the gpu-quota-admission pod is always scheduled to master node. I have to manually change gpu-manger.yaml and force the gpu-quota-admission pod to be deployed in worker node.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2.4
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by QianChenglong** [comment]
Seems like gpu-quota-admision need copy config to `/etc/kubernetes`.
![image](https://user-images.githubusercontent.com/1881126/83319434-fcd3d780-a270-11ea-9f24-fd29b8784fce.png)

@mYmNeo Maybe explain why？

**Comment by mYmNeo** [comment]
The affinity spec tell the scheduler to do so. https://github.com/tkestack/tke/blob/v1.2.4/pkg/platform/controller/addon/gpumanager/template/template.go#L165
