### ISSUE TITLE
An obvious bug when creating a new k8s cluster

### ISSUE THREAD

**Issue by ryanqin01** [tkestack/tke#410]
**What happened**:
When I'm creating a new k8s cluster using TKE, and when I choose to use GPU (by the way, it will be better if an annotation is added. I can't understand what this option is used for), it will report an error like following. I think it is an obvious bug.

![image](https://user-images.githubusercontent.com/15393045/83244333-c430f100-a1d1-11ea-9543-51fb7102ab50.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2.4
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by QianChenglong** [comment]
Known bugs, fixed in next version.
