### ISSUE TITLE
how to change the password of admin user?

### ISSUE THREAD

**Issue by ryanqin01** [tkestack/tke#496]
admin的默认密码是admin，过于简单。在用户管理界面也无法修改

![image](https://user-images.githubusercontent.com/15393045/85514483-ad45b900-b62e-11ea-8a8d-c727922a7180.png)

**Comment by wangao1236** [comment]
抱歉，目前，页面上暂时不支持修改admin密码，如果当前需要修改的话，可以手动在 global 节点上修改，具体操作步骤如下：
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin` 查看当前的 admin 用户
+ 执行 `kubectl edit cm -n tke tke-auth-controller` 修改 **tke-auth-controller.toml** 部分的 **features.tenant_admin_secret** 部分的 admin 密码
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin | grep 'usr' | awk '{print "kubectl delete localidentity "$1}' | bash`，删除当前的 admin 用户
+ 执行 `kubectl get pod -n tke | grep auth-controller | awk '{print "kubectl delete pod -n tke "$1}' | bash`，等待 tke-auth-controller 组件重启
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin` 查看，直到新的 admin 用户生成

**Comment by wangao1236** [comment]
目前，页面上暂时不支持修改admin密码，如果当前需要修改的话，可以手动在 global 节点上修改，具体操作步骤如下：
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin` 查看当前的 admin 用户
+ 执行 `kubectl edit cm -n tke tke-auth-controller` 修改 **tke-auth-controller.toml** 部分的 **features.tenant_admin_secret** 部分的 admin 密码
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin | grep 'usr' | awk '{print "kubectl delete localidentity "$1}' | bash`，删除当前的 admin 用户
+ 执行 `kubectl get pod -n tke | grep auth-controller | awk '{print "kubectl delete pod -n tke "$1}' | bash`，等待 tke-auth-controller 组件重启
+ 执行 `kubectl get localidentity --field-selector=spec.username=admin` 查看，直到新的 admin 用户生成

@ryanqin01

**Comment by ryanqin01** [comment]
可以了，谢谢。你们决定后续版本要不要支持界面修改吧，我先不关了

**Comment by ruyingzhe** [comment]
reopen #810
