### ISSUE TITLE
Integrate tapp within the organization

### ISSUE THREAD

**Issue by choujimmy** [tkestack/tke#5]
**What would you like to be added**:
Once the [`tapp`](https://github.com/tkestack/tapp) is released, a new `tapp` image needs to be integrated into tke's release package pipeline. At the same time, you need to specify the cluster's `tapp` resource forwarding in the platform api to ensure that the forwarded path matches the CRD API group and version of the `tapp`.

**Why is this needed**:
Prerequisites for publication.

**Comment by hex108** [comment]
Close via https://github.com/tkestack/tke/pull/47

/close
