### ISSUE TITLE
Install task success but cannot access console

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#52]
**Describe the bug**
Just use the tke-installer-x86_64-10fd8a9.run version to deploy tkestack, and the installation complete successfully.
But cannot access the console link, raise HTTP 502 ERROR.
Just check the pod status, found the the-gateway pod is in creating status.
The installer should check all of the components status, before sending the install task success message.
<img width="972" alt="Screen Shot 2019-12-06 at 5 38 28 PM" src="https://user-images.githubusercontent.com/35981885/70317481-ce90b480-1858-11ea-9dbe-fc5c9420116a.png">
<img width="520" alt="Screen Shot 2019-12-06 at 11 41 05 AM" src="https://user-images.githubusercontent.com/35981885/70317485-d0f30e80-1858-11ea-8f21-62ba6809ba61.png">
![Screen Shot 2019-12-06 at 11 30 51 AM](https://user-images.githubusercontent.com/35981885/70317498-d51f2c00-1858-11ea-9953-7741aeccc1d2.png)

**Environment**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - kernel: 3.10.0-957.21.3.el7.x86_64
 - docker-ce: 18.09.9

**Comment by QianChenglong** [comment]
Known issues, fixed already.
