### ISSUE TITLE
fatal: repository 'https://github.com/dovics/domain-role-manager/' not found

### ISSUE THREAD

**Issue by duyanghao** [tkestack/tke#551]
**What happened**:

tkestack `go mod vendor` failed as below:

```
go: github.com/dovics/domain-role-manager@v0.0.0-20200325101749-a44f9c315081: invalid version: git fetch -f https://github.com/dovics/domain-role-manager refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/fightingdu/go/pkg/mod/cache/vcs/a83ae2c762eb2bc44cbea25ee5959c8571d54403f6daf51e40e0dd57d859d6c4: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/dovics/domain-role-manager/' not found
``` 

**Environment**:
- TKE version: 1.3.0

**Comment by wangao1236** [comment]
I'm sorry for the problem, but this repository has been migrated to [https://github.com/amasser/domain-role-manager](https://github.com/amasser/domain-role-manager), you can be as follows, add `replace` to replace the repository in `go.mod` file to fix this problem quickly:
`github.com/dovics/domain-role-manager => github.com/amasser/domain-role-manager v0.0.0-20200325101749 - a44f9c315081`
And we will fix the problem by updating `go.mod` file as soon as possible.
