### ISSUE TITLE
Installer: add a 'pushed' tag to indicate that all images had been pushed to 3rd party registry by .

### ISSUE THREAD

**Issue by gmemcc** [tkestack/tke#576]
When using 3rd party registry,  tke images may already be pushed, just like when using offical registries. there's no need to execute load & push steps.

It is also useful to disable load & push during development phase, which will save a lot of time.

**Comment by davidwtf** [comment]
`tke-installer` has `SkipSteps` field in `Config`, see https://github.com/tkestack/tke/blob/e6de8869bf1d8995b0ebc6890822d8996bdc617c/cmd/tke-installer/app/installer/types/types.go#L46
You can add "Load Images" and "Push Images" into `skipSteps`

**Comment by gmemcc** [comment]
@davidwtf  Thanks, didn't noticed, nice feature.
