### ISSUE TITLE
query namespace by name from business list doesn't work

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#602]
业务管理 -> 选择 业务 test-business1 -> Namespace列表 -> 右上角输入框 输入 `test-ns1`, it send `http://139.155.48.141/apis/business.tkestack.io/v1/namespaces/prj-dw5mnlwb/namespaces/test-ns1` from bower , but actually should be `https://127.0.0.1:6443/apis/business.tkestack.io/v1/namespaces/prj-dw5mnlwb/namespaces/cls-cdrsctkv-test-ns1` (it works by curl).

**Comment by ruyingzhe** [comment]
fixed
