### ISSUE TITLE
node not ready because of fs.inotify.max_user_instances too small

### ISSUE THREAD

**Issue by Eric-918** [tkestack/tke#613]
**What happened**:
node status would be not ready，because of fs.inotify.max_user_instances too small 
here is issue from k8s:
https://github.com/kubernetes/kubernetes/issues/58081
https://github.com/kubernetes/kubernetes/pull/67660/files

**What you expected to happen**:

during installing, set fs.inotify.max_user_instances bigger ,like 8192 and so on 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by ruyingzhe** [comment]
this issue is more about environment, user should keep the kernel's configurations properly
