### ISSUE TITLE
get "panic: invalid registry prefix" after restart  the dockerd on tke-installer machine

### ISSUE THREAD

**Issue by ghnjk** [tkestack/tke#619]
**What happened**:

get "panic: invalid registry prefix" after restart  the dockerd on tke-installer machine
the docker log is:

goroutine 1 [running]:
tkestack.io/tke/pkg/platform/provider/baremetal/cluster.init.0()
        /data/tke/pkg/platform/provider/baremetal/cluster/provider.go:55 +0x80
Failed to find configuration provider/baremetal/conf/config.yaml
panic: invalid registry prefix

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version: 1.2.4
- Global or business cluster: global. tke-installer
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by ruyingzhe** [comment]
has fix since v1.3.0
