### ISSUE TITLE
镜像删除镜像数未变

### ISSUE THREAD

**Issue by lansedebing** [tkestack/tke#630]
组织资源->镜像仓库管理->命名空间下删除镜像，上层镜像数未做相应变化

**Comment by willemswang** [comment]
转移到开源悬赏任务：https://github.com/tkestack/tke/issues/814

**Comment by huxiaoliang** [comment]
@willemswang  what is awards to resolve this issue?

**Comment by ruyingzhe** [comment]
closed #906
