### ISSUE TITLE
cannot open FAQ installation,where is it?

### ISSUE THREAD

**Issue by ssider** [tkestack/tke#635]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by ruyingzhe** [comment]
@willemswang

**Comment by willemswang** [comment]
https://github.com/tkestack/tke/tree/master/docs/guide/zh-CN/FAQ/Installation

![image](https://user-images.githubusercontent.com/27256966/90607941-82de3980-e234-11ea-9b87-b11ba53a309e.png)

**Comment by willemswang** [comment]
https://github.com/tkestack/tke/tree/master/docs/guide/zh-CN/FAQ/Installation
