### ISSUE TITLE
tke/docs/guide/zh-CN/features/gpumanager.md 的yaml 有错误

### ISSUE THREAD

**Issue by freelw** [tkestack/tke#655]
https://github.com/tkestack/tke/blob/master/docs/guide/zh-CN/features/gpumanager.md

这里面的“tencent.com/vcuda-core: 100” 上面一行应该加上limits

**Comment by Eric-918** [comment]
https://cloud.tencent.com/developer/article/1685122
可以先参考这篇文章，稍后更新一下

**Comment by ruyingzhe** [comment]
close #793
