### ISSUE TITLE
can't delete the failed node when add node to cluster

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#660]
we can't delete failed host by UI when add host to cluster encountered `ensureXXX` failed.

to workaround, you can delete it by `kubectl`

```
kubectl delete machine xxxx
```

**Comment by ChenLingPeng** [comment]
same issue.
in my case, only run `kubectl delete machine xxxx` is not enough, the machine will go into Terminating state, I have to restart tke-platform-controller to delete machine completely

**Comment by huxiaoliang** [comment]
fixed in https://github.com/tkestack/tke/commit/ca4c66469c5b11fe8236c751a77223ff92aa233b
