### ISSUE TITLE
Cannot add node when providing non-root username

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#67]
**Describe the bug**

when creating a new cluster, specify the target node’s username and password, if input non-root username and password, the installation will get error like below:

<img width="381" alt="Screen Shot 2019-12-11 at 4 06 25 PM" src="https://user-images.githubusercontent.com/35981885/70603242-0c168880-1c31-11ea-8e93-0421912c8223.png">
<img width="771" alt="Screen Shot 2019-12-11 at 4 07 08 PM" src="https://user-images.githubusercontent.com/35981885/70603245-0de04c00-1c31-11ea-897a-c5f70b613acb.png">

>Note: User ubuntu is a valid user for the node, and it has sudo permission

**Environment**
 - OS: Ubuntu 16.04.1 LTS
 - kernel: 4.4.0-130-generic x86_64

**Comment by QianChenglong** [comment]
Must provide root privileges in order to install software and modify system configuration.
