### ISSUE TITLE
Cannot push image to registry while following the guild

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#70]
**Describe the bug**
Just follow the guide in “organization resource”->”registry management”->”your registory”->”image upload guide”,  the tag and pull commands runs into error:
the guide under “organization resource”->”access certificate” has the same problem.

<img width="548" alt="Screen Shot 2019-12-11 at 5 23 12 PM" src="https://user-images.githubusercontent.com/35981885/70611847-cf528d80-1c40-11ea-849d-506d8f13b944.png">

```log
# sudo docker tag nginx:latest https://default.registry.tke.com/myreg/nginx:latest
Error parsing reference: "https://default.registry.tke.com/myreg/nginx:latest" is not a valid repository/tag: invalid reference format
```

**Environment**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - kernel: 3.10.0-957.21.3.el7.x86_64
 - docker-ce: 18.09.9

**Comment by fleeto** [comment]
I should be
`docker tag nginx:latest  default.registry.tke.com/myreg/nginx:latest`
