### ISSUE TITLE
TKE local registry: docker push large size image failed, retrying, 504 Gateway Timeout

### ISSUE THREAD

**Issue by binji-li** [tkestack/tke#72]
**What happened**:
Use TKE local registry, then push a large image (> 2GB):
The push refers to repository 
87b1b5a611f8: Layer already exists
68dd2761fd81: Pushing [==================================================>]  2.086GB/2.086GB
received unexpected HTTP status: 504 Gateway Timeout

**Environment**:
- TKE version: v1.0.0
- Global or business cluster: global
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by choujimmy** [comment]
fixed with:
```
genericAPIServerConfig.MaxRequestBodyBytes = chartmuseum.MaxUploadSize
```
