### ISSUE TITLE
tke v1.2.5 kubectl 执行报错

### ISSUE THREAD

**Issue by attlee-wang** [tkestack/tke#725]
**What happened**:
我用 tkestack-v1.2.5安装了一个集群，然后在tke-installer docker 容器里面执行hook脚本的时候出错，经排查发现tke-installer docker 容器自带的kubectl有问题。如下图所示：

![image](https://user-images.githubusercontent.com/57479557/92730552-85046580-f3a6-11ea-99e2-41e1b7409a2d.png)

1. 我用自带的kubectl直接执行报错，如图。
2. 我搜了下错误，找到一个[issues2566](https://github.com/kubernetes/website/issues/2566)，然后用 /bin/bash -c kubectl 执行依然报错。
3. 我用[issues2566](https://github.com/kubernetes/website/issues/2566)里面的链接下载了一个kubectl，直接执行kubectl依然报错，但是当我 /bin/bash -c ./kubectl 执行的时候就正常了。

**What you expected to happen**:
希望能解释清楚这个问题，为什么kubelet会输出异常信息，到底是什么引起的？存量集群怎么解决这个的问题？

**How to reproduce it (as minimally and precisely as possible)**:
按图所示
**Anything else we need to know?**:
系统 CentOS 7.6
**Environment**:
- TKE version: v1.2.5
- Global or business cluster: Global 
- Kubernetes version (use `kubectl version`): v1.16.6
- Install addons: 
- Others:

**Comment by davidwtf** [comment]
There is a bug in 'build/docker/tool/tke-installer/release.sh'. A wrong download url cause the kubectl file is a html not binary. if  cat it, you can see the content.

You can download the correct one in your hook script or mount one into the tke-installer container.

**Comment by attlee-wang** [comment]
Thank you, Kubecll has been downloaded and mount, Running OK.
