### ISSUE TITLE
安装master时对kubelet增加参数安装集群报错

### ISSUE THREAD

**Issue by hjun881** [tkestack/tke#745]
* 环境:  阿里云ECS
* ECS系统: centos7
* 问题描述: 在tke界面通过新加集群把A服务器加入组成新的集群后再把该集群删除并在A服务器执行清除操作，然后再/etc/sysconfig/kubelet增加参数$KUBELET_EXTRA_ARGS=“--cloud-provider=external --hostname-override=cn-shenzhen-finance-1.i-j5ej4gjp7eovjcj75l00 --provider-id=cn-shenzhen-finance-1.i-j5ej4gjp7eovjcj75l00”并重新使用A服务器安装集群. 操作流程如下:

tke界面使用A服务器新建集群---> 删除该集群--->清理A服务器--->/etc/sysconfig/kubelet文件增加$KUBELET_EXTRA_ARGS变量参数--->重新在tke界面使用A服务器安装集群--->报错(报错信息如下)

kubeadm.Init error: exec cmd "kubeadm init phase upload-config all --config=/etc/kubernetes/kubeadm-config.yaml" eror: exit code 1: stderr W0917 13:40:41.222925 7833 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "tcpFinTimeout" error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition To see the stack trace of this error execute with --v=5 or higher

> 在已经有的集群下的node节点的/etc/sysconfig/kubelet文件增加$KUBELET_EXTRA_ARGS变量参数重启kubelet无报错

> 增加此参数目的主要用于安装阿里的k8s网络插件用于tke管理的k8s集群对接阿里的slb,具体可参考:https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/docs/getting-started.md

**Comment by huxiaoliang** [comment]
@leoryu please take a look this issue

**Comment by leoryu** [comment]
@hjun881 
If you are using tke to create a cluster from baremetal, `--hostname-override` is not allowed to use. `--hostname-override` will change nodename which will cause disconnection of tke and node.
Please check https://github.com/tkestack/tke/blob/master/docs/design-proposals/hostname-as-nodename-support.md for More detail about tke nodename.

**Comment by huxiaoliang** [comment]
@leoryu  we should consider the case that `--hostname-override` specified by cloud provider or end user, we should enhance here to support.

**Comment by huxiaoliang** [comment]
@hjun881 I don't have such env to verify my pr, could you please help to compile the source code for `tke-platform-api` and `tke-platform-controller` to confirm the pr is ok to you?

**Comment by huxiaoliang** [comment]
@hjun881   please follow below step to build binary to verify pr in you env, thanks in advance.

```
root@dev:~# pwd
/root/go/src/tke
root@dev:~# export VERSION=xx
root@dev:~# make build

the binary will be placed to  `_output/linux/amd64/`, then you can use `docker cp <binary>  <container-name>` and restart tke-platform-api and tke-platform-controller 
```

I am waiting for your result now.
