### ISSUE TITLE
希望增加现在集群master节点的添加与替换功能

### ISSUE THREAD

**Issue by hjun881** [tkestack/tke#746]
**What would you like to be added**:

希望增加master节点增加与替换功能

**Why is this needed**:

开始为了测试其tke的功能使用了一台服务器安装k8s的master节点,后期为了集群高可用性希望可以在现在集群增加两个master节点,但目前无法在现有集群上增加master节点

有三个master节点组成的k8s集群,因为意外挂了一个master节点并且无法恢复,然后tke实现对现在集群的master节点增加替换功能

**Comment by ruyingzhe** [comment]
close #908
