### ISSUE TITLE
tapp增加监控功能

### ISSUE THREAD

**Issue by hjun881** [tkestack/tke#769]
**What would you like to be added**:

taap工作负载添加监控的功能

**Why is this needed**:

deployment,statefulset,daemonset都有监控,但taap并没有监控如下图

![image](https://user-images.githubusercontent.com/18508499/94141144-e6e0c700-fe9e-11ea-86e6-ba9c4fd898f7.png)

![image](https://user-images.githubusercontent.com/18508499/94141177-f3fdb600-fe9e-11ea-9aef-50ffc57ea4e3.png)

**Comment by ruyingzhe** [comment]
closed #963
