### ISSUE TITLE
Console: creating business cluster with config 2048 services per cluster but got 256 services per cluster finally

### ISSUE THREAD

**Issue by binji-li** [tkestack/tke#77]
Create a business cluster with the config 2048 services per cluster on console, finally get only 256 services per cluster. And the --service-cluster-ip-range is 192.168.255.0/24, actually only support 256 services.

**Environment**:
- TKE version: v1.0.0
- Global or business cluster: business cluster
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by KayIter** [comment]
fix #77
