### ISSUE TITLE
Creating a cluster by kubectl got Unknown primitive type: "interface{}"

### ISSUE THREAD

**Issue by binji-li** [tkestack/tke#79]
\# kubectl create -f cluster2.yaml

error: SchemaError(io.tkestack.tke.pkg.monitor.services.rest.Response.data): Unknown primitive type: "interface{}"

cluster2.yaml
apiVersion: platform.tkestack.io/v1
kind: Cluster
metadata:
  generateName: cls
spec:
  apiServerExtraArgs:
    service-node-port-range: 1-65535
  displayName: cluster2
  clusterCIDR: 192.168.0.0/16
  dnsDomain: cluster.local
  features:
    ipvs: false
  finalizers:
  \- cluster
  networkDevice: eth1
  properties:
    maxClusterServiceNum: 2048
    maxNodePodNum: 256
  tenantID: default
  type: Baremetal
  version: 1.14.6
  machines:
  \- ip: xxx
    port: xxx
    username: root
    password: xxx

**Environment**:
- TKE version: v1.0.0
- Global or business cluster: Global
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by choujimmy** [comment]
fixed in e5e4d23
