### ISSUE TITLE
[Open Source Reward 2020.10.19-2020.11.19] The "Event Persistence" and "Log" components support ES domain names, ES authentication, and high version ES when docking with ElasticSearch. Difficulty: Medium

### ISSUE THREAD

**Issue by willemswang** [tkestack/tke#804]
## Requirement

**Note: Both business side and platform side must support**
> **注意：业务侧和平台侧都要支持如下能力**

## 1. ES authentication

现状：当前平台仅支持不带用户验证的 ES，但是提供公网访问的ES一定需要鉴权信息
需求：增加鉴权入口（用户选填）

Note: "ElasticSearch Address" and "Index" in the figure below are required, and "Username" and "Password" are optional
> 注意：
> 1. 下图中的“ElasticSearch地址”和“索引”为必填项，前面需要打上红色的星星。“用户名”和“密码”为选填项
> 2. 点击【检测连接】后，下方出现一行文字：“连接中…”，此时检测 ES 连接状态。若连接成功，则显示“连接成功！点击下方【完成】以设置事件持久化”；若连接失败，则显示“连接失败！请检查 ElasticSearch 相关配置，注意开启了
用户验证的 ElasticSearch 需要输入用户名和密码”
> 3. 【完成】按钮当且仅当ES检查连接成功时用户才能点击，否则置为灰色，当用户的鼠标放在灰色的“完成”上
会悬浮提示：“请检测连接 ElasticSearch，连接成功才能设置事件持久化”

Event Persistence：

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/27256966/96692237-625b6880-13b8-11eb-93c7-0f75bb91890c.png">

Log：

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/27256966/96692252-66878600-13b8-11eb-8a9c-9ceb1314036b.png">

## 2 Event Persistence support docking high version ES
The current version of fluentd used by the event component is 1.1.2, which is too low. The current test docking with ES5 is successful, but the docking with ES7 fails. The event needs to support high version ES
> 目前事件组件所使用的fluentd版本为1.1.2，版本过低，目前测试对接ES5是成功的，但对接ES7失败，需要事件支持高版本ES

## 3  ES domain names support
At present, the front-end ES address has been reviewed strictly, and it is necessary to support the input of the ES domain name address
> 目前前端ES地址审查过严，需要支持输入ES域名地址
> 注意：事件持久化和日志的该部分内容都需要修改
![image](https://user-images.githubusercontent.com/27256966/95725905-cf7d4880-0caa-11eb-8201-86acd4ceb163.png)

## 4 此处可以顺便修改一下Installer的配置审计页面

> 注意：下图中的红色*，移到方框之前，跟上面保持一样
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/27256966/96701975-ce8f9980-13c3-11eb-88c3-8982fd10bc54.png">

## Contact

willemswang@tencent.com

## Note

Everyone is welcome to participate. If more than one person participates in the same task, the first accepted PR  will be rewarded~~

欢迎大家踊跃参加，如果有多人参与了同一任务，以第一个提交并验收合格为准~~

**Comment by imlcl** [comment]
Installer 不支持 logagent-api 调用，暂无支持检测连接功能
