### ISSUE TITLE
[Open source reward 2020.10.19-2020.11.19] After the image in the registry are deleted, the number of images in the registry remains unchanged. Difficulty: low

### ISSUE THREAD

**Issue by willemswang** [tkestack/tke#814]
## Background
As shown in the figure below: delete image under Organizational Resources -> Image Registry Management -> Namespace, and the number of upper-level images has not changed accordingly

> 如下图所示：组织资源->镜像仓库管理->命名空间 下删除镜像，上层镜像数未做相应变化

**Note: Both the platform side and the business side need to be modified**

> **注意：平台侧和业务侧都需要修改**

As shown in the figure below: the image under the aa repository has been deleted, but the number of images is still 1.

> 如下图所示：aa仓库下的镜像已被删除，但是镜像数量还是为1

<img width="818" alt="image" src="https://user-images.githubusercontent.com/27256966/96449682-ce6a8f00-1247-11eb-92fb-6d2431a5c99f.png">

![image](https://user-images.githubusercontent.com/27256966/95719507-7d382980-0ca2-11eb-88f7-bda2e21e7f67.png)

## Contact

willemswang@tencent.com

## Note

Everyone is welcome to participate. If more than one person participates in the same task, the first accepted PR  will be rewarded~~

欢迎大家踊跃参加，如果有多人参与了同一任务，以第一个提交并验收合格为准~~

**Comment by TszKitLo40** [comment]
Can I try this issue?

**Comment by willemswang** [comment]
> Can I try this issue?

of course

**Comment by willemswang** [comment]
#906
