### ISSUE TITLE
[Open source reward 2020.10.19-2020.11.19] The business cluster master's taint cannot be edited. Difficulty: low

### ISSUE THREAD

**Issue by willemswang** [tkestack/tke#816]
## Description

By default, the business cluster master has an unschedulable taint: `node-role.kubernetes.io/master:NoSchedule`, and  cannot be deleted in the console. As a result, when resources are limited or there is only a master, cluster cannot create business pods.

> 业务集群master 默认带有不可调度的taint：  node-role.kubernetes.io/master:NoSchedule，且界面不可删除，导致在资源有限，或仅有master情况下，集群无法创建业务pod。

Position：
![image](https://user-images.githubusercontent.com/27256966/95733368-a1046b00-0cb4-11eb-8f87-e91f8e172517.png)

![image](https://user-images.githubusercontent.com/27256966/95730741-41589080-0cb1-11eb-8846-61ab691af56b.png)

## Requirement

此处前台支持删除/修改节点的 taint

## Contact

willemswang@tencent.com

## Note

Everyone is welcome to participate. If more than one person participates in the same task, the first accepted PR  will be rewarded~~

欢迎大家踊跃参加，如果有多人参与了同一任务，以第一个提交并验收合格为准~~

**Comment by longkai** [comment]
Hello, I am interested in fix this issue. Where is the contribution guide?

**Comment by willemswang** [comment]
> Hello, I am interested in fixing this issue. Where is the contribution guide?

sure！welcome！you can refer to this md：
docs/guide/zh-CN/catalog.md

**Comment by willemswang** [comment]
closed #933 #932

**Comment by willemswang** [comment]
#931
