### ISSUE TITLE
If set no-HA mode, should block user to add multi master node

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#82]
**What would you like to be added**:
When to install TKEStack, if If set no-HA mode, the tke-installer should block user to add multi master node

**Why is this needed**:
If set no-HA mode, there is no VIP assigned to the apiservers,  other components will connect multi apiservers address in random, that will involve risks.

**Comment by QianChenglong** [comment]
Depending on how users use it, there is no need to limit the functionality. Users can create load balancing after installation.
