### ISSUE TITLE
业务管理》应用管理》 配置管理》configMap，如果是无可用命名空间，点击新建configMap的时候，页面会进入死循环

### ISSUE THREAD

**Issue by zhaihao118** [tkestack/tke#822]
**What happened**:
业务管理 》 应用管理 》 配置管理 》 configMap 》新建
如果是无可用命名空间，点击新建的时候，页面会进入死循环。
![image](https://user-images.githubusercontent.com/12244316/96081513-fecec800-0eeb-11eb-8a2c-9a7063f26fcf.png)

**What you expected to happen**:
无可用命名空间，不能新建 configMap

**How to reproduce it (as minimally and precisely as possible)**:
官方文档使用如下命令下载，并且默认配置安装
arch=amd64 version=v1.3.1 && wget https://tke-release-1251707795.cos.ap-guangzhou.myqcloud.com/tke-installer-linux-$arch-$version.run{,.sha256} && sha256sum --check --status tke-installer-linux-$arch-$version.run.sha256 && chmod +x tke-installer-linux-$arch-$version.run && ./tke-installer-linux-$arch-$version.run
安装完成之后，再业务管理页面，配置业务的时候。

**Anything else we need to know?**:
无

**Environment**:
- TKE version:  v1.3.1
- Global or business cluster:  business cluster
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Install addons:  Prometheus Helm
- Others: none

**Comment by ruyingzhe** [comment]
Closed this issue since v1.4.0 has fix this. @zhaihao118 can reopen it if you want to cherry-pick the fix to v1.3 branch.
