### ISSUE TITLE
Fail to pull arm64 image use multi arch manifest

### ISSUE THREAD

**Issue by Beckham007** [tkestack/tke#835]
**What happened**:
docker pull tkestack/tke-gateway in arm64 machine, return error:
no matching manifrst for linux/arm64/v8 in the manifest list entries.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
docker pull tkestack/tke-gateway in arm64 machine

**Anything else we need to know?**:
build/lib/create-manifest.sh add --variant unknown for arm64

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by Beckham007** [comment]
![Uploading 404a2702-fbed-47fb-bef0-68732659d40c.jpg…]()

**Comment by ruyingzhe** [comment]
![Uploading image.png…]()
