### ISSUE TITLE
Integrate gpu-manager within the organization

### ISSUE THREAD

**Issue by choujimmy** [tkestack/tke#9]
**What would you like to be added**:
Once the [`gpu-manager`](https://github.com/tkestack/gpu-manager) is released, a new `gpu-manager` image needs to be integrated into TKE's release package pipeline. 

**Why is this needed**:
Prerequisites for publication.

**Comment by mYmNeo** [comment]
latest version tkestack/gpu-manager:1.0.3

**Comment by QianChenglong** [comment]
Fixed in current version.
