### ISSUE TITLE
Duplication of policy

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tke#90]
**Describe the bug**
There are some duplicated policies in ‘access management’->’policy management’, the policy’s name and description are same but the id is different.

<img width="1367" alt="Screen Shot 2019-12-17 at 5 42 51 PM" src="https://user-images.githubusercontent.com/35981885/70985137-9ad64a00-20f6-11ea-9ec8-57f268f9d8d6.png">

<img width="559" alt="Screen Shot 2019-12-17 at 5 44 58 PM" src="https://user-images.githubusercontent.com/35981885/70985134-9ad64a00-20f6-11ea-8a7d-5c5c477dfa1c.png">

<img width="575" alt="Screen Shot 2019-12-17 at 5 56 08 PM" src="https://user-images.githubusercontent.com/35981885/70985138-9ad64a00-20f6-11ea-8d04-833bb01623b6.png">

**Environment**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - kernel: 3.10.0-957.21.3.el7.x86_64
 - docker-ce: 18.09.9

**Comment by yadzhang** [comment]
fix by refactor_auth on future version

**Comment by yadzhang** [comment]
Use auth controller to create default policies and ensure only one.
