### ISSUE TITLE
页面安装镜像仓库设置不可用

### ISSUE THREAD

**Issue by HZ89** [tkestack/tke#949]
**What happened**:
在页面安装时，使用tke提供的regisry的选项下，installer并没有给启动一个registry，而是尝试直接使用配置的域名
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by ruyingzhe** [comment]
cannot re-produce it, installer will run the local registry when installation has started, pls check if the registry Failed or crashed.
