### ISSUE TITLE
installer安装失败

### ISSUE THREAD

**Issue by HZ89** [tkestack/tke#950]
**What happened**:
第一次installer安装失败之后删除用于保存状态的 /opt/tke-installer/data/tke.json，重启installer的容器之后，页面认为重新安装。但是安装过程不生成证书文件。

**What you expected to happen**:
提供重试按钮或者文档给出安装失败重试的标准流程

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by ruyingzhe** [comment]
follow the FAQ: https://github.com/tkestack/tke/blob/master/docs/guide/zh-CN/FAQ/Installation/%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2.md#%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85
