### ISSUE TITLE
installer检查当前状态

### ISSUE THREAD

**Issue by HZ89** [tkestack/tke#951]
**What would you like to be added**:
重试安装的时候load image步骤耗时严重，每次重试都无脑load，就不能先检查一下已经有的image的完整性，然后再决定是否loadl吗
**Why is this needed**:

**Comment by ruyingzhe** [comment]
for offline installation, tke-installer force load images to avoid the broken image. But also provide "skipSteps" parameter to let user skip some steps, like adding "skipSteps": ["Load images", "Push images"] to the request
