### ISSUE TITLE
etcd endpoint can't get update by endpoint controller 

### ISSUE THREAD

**Issue by huxiaoliang** [tkestack/tke#987]
etcd endpoint is a hard code in tkestack with master ips rather than service selector and pod label, that cause endpoint controller can't update the endpoint list according to back-end pod status for ha case

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by huxiaoliang** [comment]
solution:
1.  add  `spec.selector` to etcd service to select pod and create ep automatically 

2.  currently, etcd service and endpoint was created to `tke` namespace, but etcd pod was created by `kubeadm` to `kube-system`,  we should update the etcd client to use `etcd.kube-system` as service name when call etcd api

**Comment by davidwtf** [comment]
Don't forget add `etcd.kube-system` to etcd server's certificate.
