### ISSUE TITLE
tapp多实例，先灰度一个实例后，再修改yaml，yaml只能在没有灰度的实例上生效

### ISSUE THREAD

**Issue by fogan** [tkestack/tke#993]
在做一个一个tpp类型的pod（3实例）更新发布的时候
当我首先对其中的一个pod灰度销毁重建，另外两个实例不操作
然后去修改yaml文件，点击完成，最新的yaml在另外的这两个实例重建生效了，但是灰度实例无法生效
单独去升级也无法生效。

**Comment by ruyingzhe** [comment]
not re-produce the issue, pls check the tutorial: https://github.com/tkestack/tapp/blob/master/doc/tutorial.md#23-update-tapp, check your pod's template defination
