### ISSUE TITLE
tkestack 监控页面没有gpu-manager /metric接口相关的gpu监控数据

### ISSUE THREAD

**Issue by stubbornrock** [tkestack/tke#998]
**问题**:
tkestack 部署的独立kubernetes集群，在安装了gpu-manager 的情况下，在工作负载标签页中，查看pod或者container的监控数据，gpu相关的所有监控指标没有数值！

**环境**:
- TKE version: 1.4.0
- Global or business cluster: business cluster
- Kubernetes version (use `kubectl version`): v1.18.3 
- Install addons: 没有安装扩展插件
- Others:
启用了集群的prometheus监控

**问题发现与临时解决方案**:
**方案一**
修改集群 prometheus 对接kubernetes的配置文件，发现gpu-manager的pod，并调用其响应的 /metrics 接口进行数据拉取进监控！操作步骤如下：
1、gpu-manager 开启对接prometheus 的监控
     gpu-manager pod annotations没有中 prometheus.io/scrape: "true" 导致 prometheus 的无法对pod进行发现并监控，所以需要对gpu-manager 的 daemonset 下的 template中，添加，annotations: prometheus.io/scrape: "true"；
     临时解决操作：
     kubectl annotate pods/gpu-manager-daemonset-2hclp prometheus.io/scrape=true -n kube-system

2、prometheus.config.yaml 增加对gpu-manager pod的监控
     添加例如：
   - job_name: kubernetes-pods-(gpu-manager)
      honor_timestamps: true
      scrape_interval: 10s
      scrape_timeout: 5s
      metrics_path: /metric  #因为gpu-manager的接口是 /metric，与prometheus默认的/metrics不一致，也可以relabel_configs中修改
      scheme: http
      kubernetes_sd_configs:
      - role: pod
      tls_config:
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        separator: ;
        regex: "true"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        separator: ;
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
        action: replace
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        separator: ;
        regex: ([^:]+)(?::\d+)?;(\d+)
        target_label: __address__
        replacement: $1:$2
        action: replace
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        separator: ;
        regex: (.+)
        target_label: __scheme__
        replacement: $1
        action: replace

临时解决操作：
      prometheus.config.yaml 保存在 secrets 中需要，获取secrets 中的data，base64 反编译后，对配置文件进行修改，并最后写回到secrets中
- kubectl get secrets/prometheus-k8s-additional-scrape-config -n kube-system -o yaml > config.yaml
注意：编辑config.yaml 只保留 prometheus.config.yaml：后的base64编码值，其他的全部删除，然后对编码值进行反编码
- cat config.yaml | base64 -d > prometheus.config.yaml
添加scrape_configs中，添加 上文中的实例配置代码，再重新上传到kubernetes中
- kubectl delete secrets/prometheus-k8s-additional-scrape-config -n kube-system
- kubectl create secret generic prometheus-k8s-additional-scrape-config --from-file=prometheus.config.yaml --namespace=kube-system
prometheus 的targets: 会显示gpu-manager的endpoint
![image](https://user-images.githubusercontent.com/7532609/101754751-0cc94f80-3b0f-11eb-89c7-c94fb29a8a7b.png)

再prometheus 中查询gpu相关指标数据，labels 要与 api 请求接口的conditons一致，
![image](https://user-images.githubusercontent.com/7532609/101755625-0f787480-3b10-11eb-8dc2-6cfc0c434ce0.png)
![image](https://user-images.githubusercontent.com/7532609/101755748-346ce780-3b10-11eb-8a97-fd6f6c14759a.png)

**方案二(推荐)**
集群创建 prometheus 自带的prometheus-operator 创建的 podmonitor crd实例，operator 会自动生成prometherus 对应的scrape 的job配置文件
[root@master ~]# kubectl get podmonitors/gpu-manager -n kube-system -o yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: gpu-manager
  name: gpu-manager
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - honorLabels: true
    interval: 15s
    path: /metric
    port: metric
  selector:
    matchLabels:
      name: gpu-manager-daemonset

port: 对应的 metric 名字，可以修改gpu-manager 的 daemonset、或者 pod 进行修改
    name: gpu-manager
    ports:
    - containerPort: 5678
      name: metric
      protocol: TCP

查看prometheus 会发现自动配置的文件
- job_name: kube-system/gpu-manager/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metric
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - kube-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_name]
    separator: ;
    regex: gpu-manager-daemonset
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: metric
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: kube-system/gpu-manager
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: metric
    action: replace

**Comment by huxiaoliang** [comment]
@stubbornrock  thanks for you to report this issue with details description and solution,  if you have time fragment,  please fell free to create a pr to address this issue.
